import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const root = process.cwd();
const source = (path: string) => readFileSync(join(root, path), "utf8");

test("Prisma schema declares LibraryFetchRun with user-indexed ordering", () => {
  const schema = source("prisma/schema.prisma");
  assert.match(schema, /model LibraryFetchRun \{/);
  // Required scalar columns the fetch log relies on.
  for (const field of [
    "userId",
    "startedAt",
    "finishedAt",
    "durationMs",
    "status",
    "source",
    "cliVersion",
    "hostname",
    "platform",
    "buildersAttempted",
    "itemsFetched",
    "tasksGenerated",
    "userActionsCount",
    "errorCount",
    "summary",
    "details",
  ]) {
    assert.match(schema, new RegExp(`\\n\\s*${field}\\s+`), `LibraryFetchRun is missing ${field}`);
  }
  // details is stored as JSON (Postgres jsonb), per the schema spec.
  assert.match(schema, /details\s+Json/);
  // Cascade on user delete keeps logs from outliving the account.
  assert.match(schema, /libraryFetchRuns\s+LibraryFetchRun\[\]/);
  assert.match(schema, /libraryCronJob\s+LibraryCronJob\?/);
  assert.match(schema, /digestCronJob\s+DigestCronJob\?/);
  assert.match(
    schema,
    /model LibraryFetchRun \{[\s\S]*user\s+User\s+@relation\(fields: \[userId\], references: \[id\], onDelete: Cascade\)/,
  );
  // Index by (userId, startedAt DESC) supports the list query.
  assert.match(schema, /@@index\(\[userId, startedAt\(sort: Desc\)\]\)/);
  assert.match(schema, /model LibraryCronJob \{/);
  assert.match(schema, /intervalMinutes\s+Int/);
  assert.match(schema, /@@index\(\[userId, status\]\)/);
  assert.match(schema, /model DigestCronJob \{/);
  assert.match(schema, /regenerateDigest\s+Boolean\s+@default\(false\)/);
});

test("migration creates LibraryFetchRun with the expected columns and index", () => {
  const migration = source("prisma/migrations/000028_library_fetch_runs/migration.sql");
  assert.match(migration, /CREATE TABLE "LibraryFetchRun"/);
  assert.match(migration, /"details"\s+JSONB\s+NOT NULL/);
  assert.match(migration, /CREATE INDEX "LibraryFetchRun_userId_startedAt_idx"/);
  assert.match(migration, /REFERENCES "User"\("id"\) ON DELETE CASCADE/);
  const cronMigration = source("prisma/migrations/000041_library_cron_job/migration.sql");
  assert.match(cronMigration, /CREATE TABLE "LibraryCronJob"/);
  assert.match(cronMigration, /"intervalMinutes"\s+INTEGER\s+NOT NULL/);
  assert.match(cronMigration, /CREATE UNIQUE INDEX "LibraryCronJob_userId_key"/);
  assert.match(cronMigration, /REFERENCES "User"\("id"\)[\s\S]*ON DELETE CASCADE/);
  const digestCronMigration = source("prisma/migrations/000042_digest_cron_job/migration.sql");
  assert.match(digestCronMigration, /CREATE TABLE "DigestCronJob"/);
  assert.match(digestCronMigration, /"regenerateDigest"\s+BOOLEAN\s+NOT NULL DEFAULT false/);
  assert.match(digestCronMigration, /CREATE UNIQUE INDEX "DigestCronJob_userId_key"/);
  assert.match(digestCronMigration, /REFERENCES "User"\("id"\)[\s\S]*ON DELETE CASCADE/);
});

test("skill fetch-runs route validates payload size and gates auth on user or bearer", () => {
  const route = source("src/app/api/skill/fetch-runs/route.ts");
  const patchRoute = source("src/app/api/skill/fetch-runs/[id]/route.ts");
  const mergeHelper = source("src/lib/fetch-run-details.ts");
  const cronRoute = source("src/app/api/skill/cron-jobs/route.ts");
  // POST is bearer-token (CLI); GET is browser session or bearer read-only
  // so local production audits can read the same status model as the UI.
  assert.match(route, /getUserFromBearer\(request\)/);
  assert.match(route, /getCurrentSession\(\)/);
  assert.match(route, /export async function GET\(request: Request\)/);
  assert.match(route, /const userId = session\?\.user\?\.id \?\? bearerUser\?\.id \?\? null/);
  // Schema enforces the documented status / source enums.
  assert.match(route, /z\.enum\(\["ok", "partial", "failed"\]\)/);
  assert.match(route, /z\.enum\(\["manual", "cron"\]\)/);
  // Summary is capped at 280 chars.
  assert.match(route, /MAX_SUMMARY_CHARS = 280/);
  // details payload is rejected over 50 KB with the spec'd message.
  assert.match(route, /MAX_DETAILS_BYTES = 50_000/);
  assert.match(route, /details payload too large; cap at 50 KB/);
  // Server filters the GET by the caller's user id.
  assert.match(route, /where: \{ userId \}/);
  assert.match(route, /source: "cron"/);
  assert.match(route, /cronRuns/);
  assert.match(route, /libraryCronJob\.findUnique/);
  assert.match(route, /cronJob: cron/);
  // PATCH may append discovery-expanded tasks, but only for builders already
  // present in this run's perBuilder snapshot.
  assert.match(patchRoute, /PlannedTaskSchema/);
  assert.match(patchRoute, /plannedTasks: z\.array\(PlannedTaskSchema\)\.max\(500\)\.optional\(\)/);
  assert.match(patchRoute, /TERMINAL_FETCH_TASK_STATUSES/);
  assert.match(patchRoute, /MAX_FETCH_TASK_ID/);
  assert.match(patchRoute, /mergeFetchRunDetails/);
  assert.match(patchRoute, /workerId: z\.string\(\)\.max\(120\)\.nullable\(\)\.optional\(\)/);
  assert.match(mergeHelper, /plannedBuilderIds/);
  assert.match(mergeHelper, /details\.perBuilder/);
  // Server orders by startedAt desc and pages older history in 10-row batches.
  assert.match(route, /orderBy: \{ startedAt: "desc" \}/);
  assert.match(route, /FETCH_RUN_PAGE_SIZE = 10/);
  assert.match(route, /FETCH_RUN_QUERY_SIZE = FETCH_RUN_PAGE_SIZE \+ 1/);
  assert.match(route, /const beforeParam = url\.searchParams\.get\("before"\)/);
  assert.match(route, /startedAt: \{ lt: before \}/);
  assert.match(route, /take: FETCH_RUN_QUERY_SIZE/);
  assert.match(route, /rows\.slice\(0, FETCH_RUN_PAGE_SIZE\)\.map\(serializeRun\)/);
  assert.doesNotMatch(route, /RUN_HISTORY_LIMIT = 25/);
  assert.match(cronRoute, /getUserFromBearer\(request\)/);
  assert.match(cronRoute, /z\.enum\(\["library-cron", "digest-cron"\]\)/);
  assert.match(cronRoute, /z\.enum\(\["active", "stopped"\]\)/);
  assert.match(cronRoute, /intervalMinutes/);
  assert.match(cronRoute, /libraryCronJob\.upsert/);
  assert.match(cronRoute, /libraryCronJob\.updateMany/);
  assert.match(cronRoute, /digestCronJob\.upsert/);
  assert.match(cronRoute, /digestCronJob\.updateMany/);
  assert.match(cronRoute, /regenerateDigest/);
});

test("CLI emits a fetch-run record on both success and failure paths", () => {
  const cli = source("scripts/builder-digest.mjs");
  // CLI_VERSION is bumped for this change.
  assert.match(cli, /const CLI_VERSION = "0\.6\.0";/);
  // The CLI POSTs to the new endpoint with the bearer token.
  assert.match(cli, /\/api\/skill\/fetch-runs/);
  assert.match(cli, /BUILDER_BLOG_DISABLE_WEB_SYNC/);
  assert.match(cli, /webSyncDisabled\(\)/);
  assert.match(cli, /cron-status/);
  assert.match(cli, /\/api\/skill\/cron-jobs/);
  // Detects cron vs manual via the env variable exported by the runner.
  assert.match(cli, /BUILDER_BLOG_RUN_SOURCE/);
  // Success path logs the record after printing JSON to stdout.
  assert.match(cli, /emitFetchRunRecord\(config, \{[\s\S]*status: "ok"/);
  assert.match(cli, /emitFetchRunRecord\(config, \{[\s\S]*status: "failed"/);
  // Upload failures must not fail the command itself.
  assert.match(cli, /Failed to upload fetch log:/);
  // A failed fetch-run POST must not leave sync-builders patching a stale run id.
  assert.match(cli, /rm\(libraryFetchRunIdFile\(\), \{ force: true \}\)/);
  // Original error is printed and rethrown so the user still sees it.
  assert.match(cli, /console\.error\(message\);[\s\S]*throw error;/);
  // Fetch-run details carry an audit trail of the queued tasks plus
  // the deduped per-source-type prompts the agent was instructed with.
  assert.match(cli, /summarizeFetchTasksForLog/);
  assert.match(cli, /fetchTasks: slimFetchTasks/);
  assert.match(cli, /prompts: promptsBySourceType/);
  assert.match(cli, /Read \$\{itemsFetched\} post/);
  assert.doesNotMatch(cli, /Fetched \$\{itemsFetched\} post/);
  assert.doesNotMatch(cli, /Synced \$\{itemsFetched\} post/);
  assert.match(cli, /JOB_RUN_UPDATE_TIMEOUT_MS/);
  assert.match(cli, /\/api\/skill\/job-runs[\s\S]*timeoutMs: JOB_RUN_UPDATE_TIMEOUT_MS/);
  assert.match(cli, /HTTP \$\{details\.method\} \$\{details\.url\} \$\{message\}/);
  assert.match(cli, /timed out after \$\{Math\.round\(options\.timeoutMs \/ 1000\)\}s/);
  // Product Hunt direct-fetch 403s are recoverable: they should be shown as a
  // fallback note while agent discovery continues, not counted as a source error.
  assert.match(cli, /isRecoverableFetchFallback/);
  assert.match(cli, /builderStat\.fallback = sourceFallbackNotice\(task, message\)/);
  assert.match(cli, /agentWorkType === "fetch_builder_fallback"/);
  assert.match(cli, /Initial source scan stopped; Local Agent fallback was queued\./);
  assert.match(cli, /else \{[\s\S]*builderStat\.error = message;[\s\S]*errorCount \+= 1;/);
  // Expanded candidate discovery is a pre-post event, not a post task outcome
  // patched into details.fetchTasks.
  assert.match(cli, /discoveryExpansions/);
  assert.match(cli, /discoveryExpansionById/);
  assert.match(cli, /discovery_expanded/);
  assert.match(cli, /buildFetchRunSyncPatch/);
  assert.match(cli, /fetchRun: buildFetchRunSyncPatch/);
  assert.doesNotMatch(cli, /discoveryExpanded: true/);
});

test("builder sync endpoint durably patches fetch-run outcomes server-side", () => {
  const buildersRoute = source("src/app/api/skill/builders/route.ts");
  const contracts = source("src/lib/skill-contracts.ts");

  assert.match(contracts, /MAX_FETCH_TASK_ID = 500/);
  assert.match(contracts, /SkillFetchRunPlannedTaskSchema/);
  assert.match(contracts, /fetchRun: z\.object/);
  assert.match(buildersRoute, /mergeFetchRunDetails/);
  assert.match(buildersRoute, /parsed\.data\.fetchRun/);
  assert.match(buildersRoute, /patchFetchRunForBuilderSync/);
  assert.match(buildersRoute, /fetchRunPatch/);
  assert.match(buildersRoute, /itemResultsToFetchRunOutcomes/);
  assert.match(buildersRoute, /skillTaskOutcomeToFetchRunOutcome/);
  assert.match(buildersRoute, /builderSyncFailureResponse/);
  assert.match(buildersRoute, /catch \(error\)[\s\S]*builderSyncFailureResponse/);
  assert.match(buildersRoute, /patchFetchRunForBuilderSync[\s\S]*itemResults/);
});

test("agent runner tags cron-driven CLI runs as source=cron", () => {
  const runner = source("scripts/builder-agent-runner.sh");
  assert.match(runner, /BUILDER_BLOG_RUN_SOURCE=cron/);
  assert.match(runner, /export[^\n]*BUILDER_BLOG_RUN_SOURCE/);
  assert.match(runner, /run_cron_supervisor/);
  assert.match(runner, /run_cron_scheduler_tick/);
  assert.match(runner, /run_cron_worker/);
  assert.match(runner, /BUILDER_BLOG_SCHEDULER_TICK/);
  assert.match(runner, /ACCOUNT_SLUG/);
  assert.match(runner, /CURRENT_FILE="\$JOB_TMP_DIR\/current\.json"/);
  assert.match(runner, /BUILDER_BLOG_JOB_TMP_DIR/);
  assert.match(runner, /write_current_file "\$CURRENT_FILE" "\$INSTANCE_ID" "\$BUILDER_BLOG_WORKER_PID"/);
  assert.match(runner, /write_current_file "\$CURRENT_FILE" "\$INSTANCE_ID" "\$WORKER_PID"/);
  assert.match(runner, /WORKER_PID="\$\$"/);
  assert.match(runner, /BUILDER_BLOG_SKIP_BOOTSTRAP_REFRESH/);
  assert.match(runner, /worker_bootstrap_failed/);
  assert.match(runner, /worker_prompt_missing/);
  assert.match(runner, /Scheduled worker running in launchd foreground/);
  assert.match(runner, /Running scheduled window \$EXPECTED_AT as pid \$WORKER_PID/);
  assert.match(runner, /exec "\$0" "\$JOB_NAME"/);
  assert.doesNotMatch(runner, /WORKER_PID="\$!"/);
  assert.match(runner, /verify_followbrief_pid/);
  assert.match(runner, /terminate_process_tree/);
  assert.match(runner, /process_tree_pids/);
  assert.match(runner, /worker_shard_timeout/);
  assert.match(runner, /shard_timeout_seconds\(\)/);
  assert.match(runner, /_shard_timeout="\$\(shard_timeout_seconds "\$_whole_timeout"\)"/);
  assert.match(runner, /validation-failed-payload\.json/);
  assert.match(runner, /--exclude-task-ids-file "\$_checkpoint_synced_ids_file"/);
  assert.match(runner, /--reason "validation_failed"/);
  assert.match(runner, /patch-fetch-run-plan/);
  assert.match(runner, /--partial-outcomes/);
  assert.match(runner, /still_alive_after_kill/);
  assert.match(runner, /skipped-wait-pids/);
  assert.match(runner, /job_run_update_for_instance/);
  assert.match(runner, /stale_pid_next_schedule_arrived/);
  assert.match(runner, /OLD_STARTED="\$\(json_get_string startedAt "\$CURRENT_FILE"\)"/);
  assert.match(runner, /OLD_EXPECTED="\$\(json_get_string expectedAt "\$CURRENT_FILE"\)"/);
  assert.match(runner, /toleranceMs = Math\.min\(5 \* 60 \* 1000/);
  assert.match(runner, /elapsed \+ toleranceMs < intervalMs/);
  assert.match(runner, /status replaced/);
  assert.match(runner, /status killed/);
  assert.match(runner, /\*\-cron\)/);
});

test("CLI can audit production cron status against local scheduler state", () => {
  const cli = source("scripts/builder-digest.mjs");

  assert.match(cli, /fetch-status-audit/);
  assert.match(cli, /async function fetchStatusAudit\(\)/);
  assert.match(cli, /\/api\/skill\/fetch-runs/);
  assert.match(cli, /schedule-anchor-library-cron-\$\{accountSlug\(\)\}/);
  assert.match(cli, /last-fired-expected-at/);
  assert.match(cli, /current\.json/);
  assert.match(cli, /production_cron_active/);
  assert.match(cli, /local_anchor_matches_production/);
  assert.match(cli, /latest_scheduled_run_terminal/);
  assert.match(cli, /last_fired_matches_latest_scheduled_run/);
  assert.match(cli, /current_file_not_dead/);
  assert.match(cli, /digest-status-audit/);
  assert.match(cli, /async function digestStatusAudit\(\)/);
  assert.match(cli, /\/api\/digest-runs/);
  assert.match(cli, /schedule-anchor-digest-cron-\$\{accountSlug\(\)\}/);
  assert.match(cli, /latest_digest_run_synced_for_scheduled_job/);
});

test("FetchLogPanel renders status pills and modal-only logs with semantic CSS variables", () => {
  const panel = source("src/components/FetchLogPanel.tsx");
  assert.match(panel, /@\/lib\/schedule-timing/);
  assert.doesNotMatch(panel, /function floorToExpectedSchedule/);
  assert.doesNotMatch(panel, /function addScheduleInterval/);
  // Status pill colors must reuse existing tokens, not new colors.
  assert.match(panel, /var\(--signal\)/);
  assert.match(panel, /var\(--warm\)/);
  assert.match(panel, /var\(--danger\)/);
  // Background refresh still calls the GET endpoint, but the panel no longer
  // renders its own manual Refresh button.
  assert.match(panel, /fetch\("\/api\/skill\/fetch-runs"/);
  assert.match(panel, /if \(response\.status === 401\) \{[\s\S]*setError\(null\);[\s\S]*return;[\s\S]*\}/);
  assert.doesNotMatch(panel, /RefreshCw/);
  assert.doesNotMatch(panel, />Refresh</);
  assert.doesNotMatch(panel, /VISIBLE_RUN_LIMIT = 2/);
  assert.doesNotMatch(panel, /role="tablist"/);
  assert.doesNotMatch(panel, /onKeyDown=\{handleTabKeyDown\}/);
  assert.doesNotMatch(panel, /tabIndex=\{activeTab ===/);
  assert.doesNotMatch(panel, /fb-segmented-tabs/);
  assert.doesNotMatch(panel, /id="fetch-sync-tab-status"/);
  assert.doesNotMatch(panel, /id="fetch-sync-tab-log"/);
  assert.doesNotMatch(panel, /id="fetch-sync-panel-log"/);
  assert.doesNotMatch(panel, /role="tabpanel"/);
  assert.doesNotMatch(panel, /Fetch status/);
  assert.match(panel, /Fetch log/);
  assert.doesNotMatch(panel, /Fetch sources run history/);
  assert.doesNotMatch(panel, /function FetchRunList/);
  assert.doesNotMatch(panel, /className="sync-panel-run-list-shell"/);
  assert.doesNotMatch(panel, /aria-label="Fetch sources run history list"/);
  assert.doesNotMatch(panel, /className="sync-panel-run-list sync-panel-run-list-scroll"/);
  assert.match(panel, /fallback\?:/);
  assert.match(panel, /function mergeFetchRunLists/);
  assert.doesNotMatch(panel, /if \(!byId\.has\(run\.id\)\) byId\.set\(run\.id, run\)/);
  assert.match(panel, /byId\.set\(run\.id, run\)/);
  assert.match(panel, /const dialogRuns = useMemo\(\(\) => mergeFetchRunLists\(runs, cronRuns\), \[runs, cronRuns\]\)/);
  assert.match(panel, /runs=\{dialogRuns\}/);
  assert.match(panel, /candidate\.jobRunId === logRef\.instanceId/);
  assert.match(panel, /const postTasks = fetchTasks\.filter\(isPlannedPostTask\)/);
  assert.match(panel, /taskWorkerGroups\(postTasks, liveTasks, fallbackTaskWorkerName\(liveProgress\)\)/);
  assert.match(panel, /function fallbackTaskWorkerName/);
  assert.match(panel, /Worker assignment pending/);
  assert.doesNotMatch(panel, /Main Local Agent/);
  assert.doesNotMatch(panel, /Technical details/);
  assert.doesNotMatch(panel, /sync-panel-task-technical/);
  assert.doesNotMatch(panel, /JSON\.stringify\(task, null, 2\)/);
  assert.match(panel, /Post task details/);
  assert.match(panel, /className="sync-panel-run-card-details-count"/);
  assert.doesNotMatch(panel, /Post tasks \(\{postTasks\.length\}\)/);
  assert.match(panel, /className="sync-panel-task-worker-group-list"/);
  assert.match(panel, /className="sync-panel-task-worker-details" open/);
  assert.match(panel, /className="sync-panel-task-worker-summary"/);
  assert.match(panel, /className="sync-panel-task-source-group-list"/);
  assert.match(panel, /className="sync-panel-task-source-details" open/);
  assert.match(panel, /taskSourceGroups\(group\.tasks\)/);
  assert.doesNotMatch(panel, /function ratioCount\(done: number, total: number\)/);
  assert.doesNotMatch(panel, /workerStats = groupedTaskStats\(workerGroup\.tasks\)/);
  assert.doesNotMatch(panel, /className="mono sync-panel-task-worker-meta"/);
  assert.match(panel, /\{formatCount\(stats\.planned\)\}<\/strong> planned/);
  assert.match(panel, /\{formatCount\(stats\.read\)\}<\/strong> read/);
  assert.match(panel, /\{formatCount\(stats\.summarized\)\}<\/strong> summarized/);
  assert.match(panel, /\{formatCount\(stats\.synced\)\}<\/strong> synced/);
  assert.doesNotMatch(panel, /\{formatCount\(workerGroup\.tasks\.length\)\}<\/strong> tasks/);
  assert.doesNotMatch(panel, /\{formatCount\(stats\.planned\)\}<\/strong> posts/);
  assert.match(panel, /function discoveryTaskState/);
  assert.match(panel, /expandedByPosts/);
  assert.match(panel, /Waiting on posts/);
  assert.match(panel, /post tasks synced/);
  assert.match(panel, /post tasks/);
  assert.doesNotMatch(panel, /sourceRunStats/);
  // A fetch run linked to a stopped/killed runtime job is no longer live even
  // if its planned task outcomes were never patched.
  assert.match(panel, /jobRunByInstanceId/);
  assert.match(panel, /cronJobRef/);
  assert.match(panel, /run\.source === "cron" && cronJob && cronJob\.status !== "active"/);
  assert.match(panel, /if \(jobRun && \(!isActiveJobRun\(jobRun\) \|\| isStalledJobRun\(jobRun\)\)\) return false/);
  assert.match(panel, /if \(jobRun && jobRun\.trigger !== "scheduled"\) return false/);
  assert.match(panel, /if \(!jobRun && run\.source !== "cron"\) return false/);
  assert.match(panel, /const postTasks = tasks\.filter\(isPlannedPostTask\)/);
  assert.match(panel, /return postTasks\.some\(\(task\) => task\?\.status === "pending" \|\| task\?\.status === "fetched"\)/);
  assert.match(panel, /function isNoUpdateFetchRun/);
  assert.match(panel, /label: "No update"/);
  assert.match(panel, /No update\. Sources were checked and no new posts needed to be saved\./);
  assert.match(panel, /if \(cronJob\.status !== "active"\) \{[\s\S]*key: "stopped"/);
  assert.match(panel, /<RunCard cronJob=\{cronJob\} domId=\{null\} jobRun=\{resolvedJobRun \?\? undefined\} run=\{run\} \/>/);
  assert.match(source("scripts/builder-agent-runner.sh"), /patch-fetch-run-plan[\s\S]*--results-dir "\$_results_dir"/);
  assert.match(panel, /interruptedFetchRunStatus/);
  assert.match(panel, /label: "Stopped"/);
  assert.match(panel, /isStalledJobRun\(jobRun\)[\s\S]*label: "Stalled"/);
  assert.match(panel, /Local Agent stopped reporting before final sync outcomes arrived\./);
  assert.match(panel, /type JobRunDiagnosticItem/);
  assert.match(panel, /function RunCardVerdict/);
  assert.match(panel, /className="sync-panel-run-card-verdict-text"/);
  assert.match(panel, /className="sync-panel-run-card-diagnostics"/);
  assert.doesNotMatch(panel, /className="mono sync-panel-run-card-stage"/);
  assert.match(panel, /const displayStatus = inflight/);
  assert.match(panel, /displayStatus\.label/);
  assert.match(panel, /statusToneClass\(displayStatus\.tone\)/);
  assert.doesNotMatch(panel, /displayStatus\.style\.background/);
  assert.match(source("src/lib/scheduled-window-ui.ts"), /case "stale":[\s\S]*return "Stopped"/);
  assert.match(panel, /latestSlot\?\.status === "running"/);
  assert.match(panel, /The current scheduled Fetch sources run is still in progress/);
  assert.match(panel, /latestSlot\?\.status === "stalled"/);
  assert.match(panel, /FollowBrief lost contact with the latest scheduled Fetch sources run/);
  assert.match(panel, /const nextExpectedMs = nextExpected\.getTime\(\)/);
  assert.match(panel, /nextExpectedMs > nowMs/);
  assert.match(panel, /expected\.push\(nextExpected\)/);
  assert.match(panel, /function timelineSlotSyncSummary/);
  assert.match(panel, /if \(!run && !jobRun\) return null/);
  assert.match(panel, /const latestDueSlot = slots\.slice\(\)\.reverse\(\)\.find\(\(slot\) => Date\.parse\(slot\.expectedAt\) <= Date\.now\(\)\) \?\? null/);
  assert.doesNotMatch(panel, /sync-panel-status-graph/);
  assert.doesNotMatch(panel, /sync-panel-slot-bar/);
  assert.doesNotMatch(panel, /FetchTimelineBar/);
  assert.doesNotMatch(panel, /visibleGraphEntries|graphStartLabel|graphEndLabel/);
  assert.match(panel, /className="sync-panel-slot-rows is-scrollable is-timeline" onScroll=\{handleLogScroll\}/);
  assert.doesNotMatch(panel, />Oldest</);
  assert.doesNotMatch(panel, />Newest</);
  assert.match(panel, /No Fetch sources run started in the latest scheduled window/);
  assert.doesNotMatch(panel, /The latest scheduled Fetch sources run did not report back/);
  assert.match(panel, /timeoutSeconds/);
  assert.match(panel, /Timed out after \$\{formatDuration\(details\.timeoutSeconds \* 1000\)\}/);
  assert.match(panel, /Cleanup did not finish/);
  assert.match(panel, /function isInternalJobRunReason/);
  assert.match(panel, /reason === "heartbeat"/);
  assert.match(panel, /reason === "timeout_seconds_for_job"/);
  assert.match(panel, /const reason = isInternalJobRunReason\(details\.reason\) \? null : humanizeJobRunCode\(details\.reason\)/);
  assert.doesNotMatch(panel, /timedOutWorkerPid \? `pid/);
  assert.doesNotMatch(panel, /Green OK|amber waiting|red issue/);
  assert.doesNotMatch(panel, /className="sync-panel-metrics"/);
  assert.doesNotMatch(panel, /CountMetric/);
  assert.match(panel, /function runMatchesJobRun/);
  assert.match(panel, /function timelineSlotRun/);
  assert.match(panel, /function timelineSlotLogRef/);
  assert.match(panel, /function timelineSlotRunNote/);
  assert.match(panel, /function timelineSlotSyncSummary/);
  assert.match(panel, /const run = timelineSlotRun\(slot\)/);
  assert.match(panel, /const logRef = timelineSlotLogRef\(slot, run\)/);
  assert.match(panel, /if \(run\) matchedRunIds\.add\(run\.id\)/);
  assert.match(panel, /if \(slot\.run\) return \{ kind: "run", runId: slot\.run\.id \}/);
  assert.match(panel, /if \(slot\.run\) matchedRunIds\.add\(slot\.run\.id\)/);
  assert.match(panel, /const FETCH_LOG_PAGE_SIZE = 10/);
  assert.doesNotMatch(panel, /const LOG_WINDOW_SIZE = 6/);
  assert.doesNotMatch(panel, /function visibleLogWindowStart/);
  assert.match(panel, /function oldestFetchHistoryCursor/);
  assert.match(panel, /function shouldLoadMoreHistory/);
  assert.match(panel, /const loadMoreHistory = useCallback/);
  assert.match(panel, /before=\$\{encodeURIComponent\(cursor\)\}/);
  assert.match(panel, /setRuns\(\(current\) => mergeFetchRunLists\(current, bodyRuns\)\)/);
  assert.match(panel, /hasMoreFetchHistory/);
  assert.match(panel, /const rowEntries = useMemo\(\(\) => entries\.slice\(\)\.reverse\(\), \[entries\]\)/);
  assert.match(panel, /const hasScrollCue = rowEntries\.length > 3 \|\| hasMoreHistory \|\| isLoadingHistory/);
  assert.doesNotMatch(panel, /const visibleRowEntries = rowEntries\.slice\(logWindowStart, logWindowStart \+ LOG_WINDOW_SIZE\)/);
  assert.doesNotMatch(panel, /visibleGraphEntries\.map/);
  assert.match(panel, /className=\{`sync-panel-scroll-cue\$\{hasScrollCue \? " has-more" : ""\}`\}/);
  assert.match(panel, /className="sync-panel-slot-rows is-scrollable is-timeline" onScroll=\{handleLogScroll\}/);
  assert.match(panel, /className="sync-panel-slot-loading"/);
  assert.match(panel, /data-sync-log-row="true"/);
  assert.match(source("src/app/globals.css"), /--sync-panel-visible-log-rows: 3/);
  assert.match(source("src/app/globals.css"), /\.sync-panel-scroll-cue\.has-more::after/);
  assert.doesNotMatch(source("src/app/globals.css"), /max-height: calc\(6 \* 3\.25rem/);
  assert.doesNotMatch(panel, /\.slice\(-CRON_SLOT_LIMIT\)/);
  assert.match(panel, /function formatRunSyncSummary\(done: number \| undefined, total: number \| undefined\): string/);
  assert.match(panel, /return `\$\{formatCount\(synced\)\}\/\$\{formatCount\(planned\)\} saved`/);
  assert.match(panel, /const hasDetailedPostTasks = Array\.isArray\(details\.fetchTasks\) && details\.fetchTasks\.filter\(isPlannedPostTask\)\.length > 0/);
  assert.match(panel, /\? Math\.max\(stats\.planned, stats\.synced\)[\s\S]*: Math\.max\(stats\.planned, run\.tasksGenerated, run\.itemsFetched, stats\.synced\)/);
  assert.doesNotMatch(panel, /if \(planned <= 0 && synced <= 0\) return null/);
  assert.doesNotMatch(panel, /cronSlotRunNote/);
  assert.match(panel, /@\/lib\/scheduled-window-ui/);
  assert.match(panel, /scheduledWindowStatusLabel/);
  assert.match(panel, /scheduledWindowStyleStatus/);
  assert.match(panel, /scheduledWindowRunNote/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun, "library-cron"\)/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun, "library-cron"\)/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun \?\? null, "library-cron", run\.source\)/);
  assert.match(panel, /const noUpdate = isNoUpdateFetchRun\(entry\.run, entry\.jobRun\)/);
  assert.match(panel, /const displayTone = noUpdate \? "ok" : tone/);
  assert.match(panel, /const statusLabel = noUpdate \? "No update" : scheduledWindowStatusLabel\(entry\.status\)/);
  assert.match(panel, /ok: "Succeeded"/);
  assert.match(panel, /if \(jobRun\.status === "killed" \|\| jobRun\.status === "stale"\) return "Stopped"/);
  assert.match(panel, /function runHeaderMeta/);
  assert.match(panel, /function runHeaderHost/);
  assert.match(panel, /jobRunStatusLabel\(slot\.jobRun\)/);
  assert.match(panel, /actionsPlacement = "end"/);
  assert.match(panel, /actionsPlacement === "start"/);
  assert.match(panel, /className="source-fetch-overview"/);
  assert.doesNotMatch(panel, /Use Update sources to copy a Local Agent prompt/);
  assert.doesNotMatch(panel, /Schedule stopped[\s\S]{0,120}Local Agent prompt/);
  assert.match(panel, /Needs Local Agent/);
  assert.match(panel, /taskStatusPill/);
  assert.match(panel, /return \{ label: "summarizing", tone: "warn" \}/);
  assert.match(panel, /return \{ label: "reading", tone: "idle" \}/);
  assert.match(panel, /return \{ label: "syncing", tone: "warn" \}/);
  assert.match(panel, /return \{ label: "discovering", tone: "warn" \}/);
  assert.match(panel, /return \{ label: "failed", tone: "fail" \}/);
  assert.doesNotMatch(panel, /task\.contentStatus === "ready"\) return "ready"/);
  assert.match(panel, /isCandidateDiscoveryTask/);
  assert.doesNotMatch(panel, /return \{ label: "expanded", tone: "ok" \}/);
  assert.match(panel, /Candidates discovered/);
  assert.match(panel, /label: isDiscovery \? "Expand" : "Summarize"/);
  assert.match(panel, /function hasReadSignal/);
  assert.match(panel, /statusBanner\(task, liveTask\)/);
  assert.match(panel, /Waiting for Local Agent/);
  assert.match(panel, /Read has not completed yet, so summary has not started\./);
  assert.match(panel, /Discovery task lifecycle/);
  assert.match(panel, /Expanded into/);
  assert.doesNotMatch(panel, /\{ready \? "ready" : "Local Agent"\}/);
  assert.match(panel, /<FactRow label="Local Agent"/);
  assert.doesNotMatch(panel, /Read by helper|<FactRow label="Helper"|\{ready \? "ready" : "helper"\}/);
  assert.match(panel, /digest-updates-panel/);
  assert.match(panel, /FetchStatusToggle/);
  assert.match(panel, /SourceFetchMetaGrid/);
  assert.match(panel, /getFetchActivityStatus\(timelineEntries\)/);
  assert.match(panel, /fetchCronFrequencyLabel\(cronJob\)/);
  assert.doesNotMatch(panel, /status=\{updateStatus\}/);
  assert.match(panel, /SourceFetchMetaItem/);
  assert.match(panel, /aria-label="Fetch sources details"/);
  assert.doesNotMatch(panel, /aria-label="Source update details"/);
  assert.match(panel, /Fetch frequency/);
  assert.doesNotMatch(panel, /Update frequency/);
  assert.match(panel, /Language/);
  assert.match(panel, /Latest fetch/);
  assert.match(panel, /Status \/ log/);
  assert.doesNotMatch(panel, /Schedule status/);
  assert.doesNotMatch(panel, /Cron status/);
  assert.match(panel, /formatLanguage\(summaryLanguage \?\? "zh"\)/);
  assert.match(panel, /displayLanguagePreference\(value\)/);
  assert.match(panel, /formatMetaDate\(latestRun\.startedAt, hydrated\)/);
  assert.match(panel, /function formatMetaDate\(iso: string, hydrated: boolean\)/);
  assert.match(panel, /if \(!hydrated\) return formatAbsolute\(iso\)/);
  assert.match(panel, /aria-controls="fetch-sync-details"/);
  assert.match(panel, /className="sync-panel-error"/);
  assert.match(panel, /className="sync-panel-run-card sync-panel-fetch-run-card sync-panel-mobile-flat"/);
  assert.match(panel, /className="sync-panel-run-card-head"/);
  assert.match(panel, /className="sync-panel-run-card-head-main"/);
  assert.match(panel, /className="sync-panel-run-card-head-meta"/);
  assert.match(panel, /className="sync-panel-run-card-summary"/);
  assert.doesNotMatch(panel, /className="mono sync-panel-run-card-meta"/);
  assert.doesNotMatch(panel, /sync-panel-run-card-stage/);
  assert.match(panel, /className="sync-panel-run-card-details"/);
  assert.match(panel, /className="sync-panel-run-card-details-summary"/);
  assert.match(panel, /className="sync-panel-run-card-details-body"/);
  assert.match(panel, /className="sync-panel-run-card-details-stack"/);
  assert.match(panel, /className="sync-panel-task-worker-group"/);
  assert.doesNotMatch(panel, /className="mono sync-panel-task-worker-meta"/);
  assert.match(panel, /className="sync-panel-task-source-group"/);
  assert.match(panel, /className="mono sync-panel-task-source-meta"/);
  assert.match(panel, /className="sync-panel-status-brief"/);
  assert.match(panel, /className="sync-panel-layout is-log-only"/);
  assert.match(panel, /<dt>Schedule enabled<\/dt>/);
  assert.doesNotMatch(panel, /<dt>Next scheduled run<\/dt>/);
  assert.match(panel, /<dt>Runner<\/dt>/);
  assert.match(panel, /<RunCardVerdict details=\{diagnostic\} text=\{verdict\.text\} tone=\{verdict\.tone\} \/>/);
  assert.match(source("src/app/globals.css"), /\.sync-panel-run-card-diagnostics\s*{/);
  assert.match(source("src/app/globals.css"), /\.sync-panel-run-card-verdict-text\s*{/);
  assert.doesNotMatch(panel, /className="sync-panel-run-card-funnel"/);
  assert.doesNotMatch(panel, /className=\{`sync-panel-slot-bar \$\{heightClass\}`\}/);
  assert.match(panel, /className="sync-panel-slot-row"/);
  assert.match(panel, /className="sync-panel-slot-row-main"/);
  assert.match(panel, /className="sync-panel-slot-row-primary"/);
  assert.match(panel, /className="sync-panel-slot-row-secondary"/);
  assert.match(panel, /className="sync-panel-slot-row-side"/);
  assert.match(panel, /className=\{`sync-panel-slot-row-status \$\{statusToneClass\(displayTone\)\}`\}/);
  assert.match(panel, /className="sync-panel-slot-row-dot"/);
  assert.doesNotMatch(panel, /style=\{\{ color: style\.color \}\}/);
  assert.doesNotMatch(panel, /style=\{\{ background: style\.color \}\}/);
  assert.match(panel, /className="sync-panel-slot-row-kind"/);
  assert.match(panel, /className="sync-panel-slot-row-time"/);
  assert.match(panel, /className="mono sync-panel-slot-row-note"/);
  assert.match(panel, /\{entry\.syncSummary \? \(/);
  assert.match(panel, /\{entry\.syncSummary\}<\/span>/);
  assert.doesNotMatch(panel, /\{entry\.note\}<\/span>/);
  assert.doesNotMatch(panel, /sync-panel-chip-row/);
  assert.doesNotMatch(panel, /refreshes library posts/);
  assert.doesNotMatch(panel, /one-time only/);
  assert.doesNotMatch(panel, /slice\(0, 6\)/);
  assert.match(panel, /className="sync-panel-stopped-time"/);
  assert.doesNotMatch(panel, /className="sync-panel-see-more-label"/);
  assert.match(panel, /className=\{`fb-chip \$\{statusToneClass\(displayStatus\.tone\)\}\$\{inflight \? " sync-panel-live-chip" : ""\}`\}/);
  assert.match(panel, /label: "Syncing"/);
  assert.doesNotMatch(panel, /Updating…/);
  assert.match(panel, /className="sync-panel-run-card-live-dot"/);
  assert.doesNotMatch(panel, /className="mt-2 text-\[12\.5px\] leading-relaxed"/);
  assert.doesNotMatch(panel, /className="block min-w-0 flex-1 cursor-pointer rounded-sm border/);
  assert.doesNotMatch(panel, /className="flex flex-wrap items-center justify-between gap-2 rounded-\[7px\] px-1 py-1 text-\[12\.5px\] target:bg-\[var\(--accent-soft\)\]"/);
  assert.doesNotMatch(panel, /className="text-\[12\.5px\] text-\[var\(--muted-strong\)\]"/);
  assert.doesNotMatch(panel, /className="mono truncate text-\[11\.5px\] text-\[var\(--muted-strong\)\]"/);
  assert.doesNotMatch(panel, /className="fb-chip inline-flex items-center gap-1\.5"/);
  assert.match(panel, /className="sync-panel-task-card fb-task"/);
  assert.match(panel, /className="sync-panel-task-summary fb-task-summary"/);
  assert.match(panel, /className="sync-panel-task-chev fb-task-chev"/);
  assert.doesNotMatch(panel, /className="sync-panel-task-source-type"/);
  assert.doesNotMatch(panel, /\{group\.sourceType\}<\/span>/);
  assert.match(panel, /aria-label=\{`\$\{group\.name\}: \$\{stats\.planned\} planned, \$\{stats\.read\} read, \$\{stats\.summarized\} summarized, \$\{stats\.synced\} synced`\}/);
  assert.match(panel, /className=\{`sync-panel-task-status-pill is-\$\{pill\.tone\}`\}/);
  assert.match(panel, /className="sync-panel-task-title"/);
  assert.doesNotMatch(panel, /className="sync-panel-task-builder"/);
  assert.match(panel, /className="sync-panel-task-body"/);
  assert.match(panel, /className=\{`sync-panel-task-banner is-\$\{banner\.tone\}`\}/);
  assert.match(panel, /className=\{`sync-panel-task-banner is-\$\{liveTone\}`\}/);
  assert.match(panel, /Fetch is running\. Stages update as Local Agent reports work\./);
  assert.match(panel, /Completed\. Planned posts were read, summarized, and synced or accounted for\./);
  assert.match(panel, /\$\{countNoun\(unfinished, "planned post"\)\} did not finish before sync finished\./);
  assert.match(panel, /Local Agent stopped before FollowBrief received final sync outcomes\./);
  assert.match(panel, /Planned posts recorded; some still lack final sync outcomes\./);
  assert.doesNotMatch(panel, /stats\.failed \|\| 1|Fetch is still running|Stage progress below|explicitly accounted for|Planned posts were recorded, but some still lack a final sync outcome|Run recorded planned posts, but not every post has a final sync outcome yet/);
  assert.match(panel, /className="sync-panel-lifecycle"/);
  assert.match(panel, /className=\{`sync-panel-lifecycle-step is-\$\{step\.tone\}`\}/);
  assert.match(panel, /className="sync-panel-task-fact-row"/);
  assert.match(panel, /className="sync-panel-detail-note"/);
  assert.match(panel, /Prompts used to read and summarize each source type in this update\./);
  assert.match(panel, /Prompt instructions/);
  assert.doesNotMatch(panel, /Helper instructions/);
  assert.doesNotMatch(panel, /The instructions used to read and summarize each source type/);
  assert.match(panel, /className="sync-panel-detail-card-list"/);
  assert.match(panel, /className="sync-panel-detail-card"/);
  assert.match(panel, /className="sync-panel-detail-card-summary"/);
  assert.match(panel, /className="sync-panel-detail-card-body"/);
  assert.match(panel, /className="sync-panel-detail-kicker"/);
  assert.match(panel, /className="sync-panel-detail-kicker-row"/);
  assert.match(panel, /className="sync-panel-detail-default-pill"/);
  assert.match(panel, /No fetch prompt set for this source; using common fetching rules\./);
  assert.doesNotMatch(panel, /No fetch prompt is configured for this source; the Local Agent used common fetching rules\./);
  assert.match(panel, /className="mono sync-panel-detail-code"/);
  assert.match(panel, /className="sync-panel-detail-action-list"/);
  assert.match(panel, /className="sync-panel-detail-action-row"/);
  assert.match(panel, /className="sync-panel-detail-link"/);
  assert.match(panel, /className="sync-panel-detail-error-list"/);
  assert.match(panel, /className="mono sync-panel-detail-error-row"/);
  assert.match(panel, /className="mono sync-panel-detail-json"/);
  assert.match(panel, /className="sync-panel-detail-empty"/);
  assert.doesNotMatch(panel, /className="rounded-\[10px\] border bg-\[var\(--paper-strong\)\] px-3\.5 py-3"/);
  assert.doesNotMatch(panel, /className="mt-2 rounded-\[8px\] border border-\[var\(--line\)\] bg-\[var\(--paper\)\]"/);
  assert.doesNotMatch(panel, /className="fb-task rounded-\[8px\] border border-\[var\(--line\)\] bg-\[var\(--paper-strong\)\]"/);
  assert.doesNotMatch(panel, /className="fb-task-summary flex items-center gap-1\.5 px-2\.5 py-1\.5 text-\[12\.5px\] leading-snug"/);
  assert.doesNotMatch(panel, /className="flex gap-2 text-\[12px\] leading-relaxed"/);
  assert.doesNotMatch(panel, /className="rounded-\[6px\] px-2\.5 py-1\.5 text-\[12px\] font-bold"/);
  assert.doesNotMatch(panel, /className="mt-2 grid gap-2"/);
  assert.doesNotMatch(panel, /className="rounded-\[8px\] border border-\[var\(--line\)\] bg-\[var\(--paper-strong\)\]"/);
  assert.doesNotMatch(panel, /className="mono mt-1 max-h-72 overflow-auto whitespace-pre-wrap text-\[11\.5px\]"/);
  assert.doesNotMatch(panel, /digest-updates-head[\s\S]{0,360}flex flex-wrap items-center gap-2/);
  assert.doesNotMatch(panel, /error \? \([\s\S]{0,120}mt-3 text-\[12px\] text-\[var\(--danger\)\]/);
  assert.doesNotMatch(panel, /Fetch schedule status graph/);
  assert.match(panel, /buildCronStatus/);
  assert.match(panel, /buildFetchTimeline/);
  assert.match(panel, /type FetchTimelineEntry/);
  assert.match(panel, /type FetchLogRef/);
  assert.match(panel, /selectedLog/);
  assert.match(panel, /FetchLogDialog/);
  assert.match(panel, /role="dialog"/);
  assert.match(panel, /aria-modal="true"/);
  assert.match(panel, /<h3>Fetch log<\/h3>/);
  assert.doesNotMatch(panel, /sync-panel-detail-kicker[\s\S]{0,80}Fetch log/);
  assert.match(panel, /onOpenLog/);
  assert.doesNotMatch(panel, /FetchTimelineBar/);
  assert.match(panel, /FetchTimelineRow/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun \?\? null, "library-cron", run\.source\)/);
  assert.match(panel, /slotDomId/);
  assert.match(panel, /runDomId/);
  assert.match(panel, /jobRunDomId/);
  assert.doesNotMatch(panel, /onOpenRun/);
  assert.match(panel, /const openLog = useCallback\(\(logRef: FetchLogRef\) => \{[\s\S]*setDetailsOpen\(true\);[\s\S]*setSelectedLog\(logRef\);[\s\S]*\}, \[\]\);/);
  assert.match(panel, /Open log/);
  assert.match(panel, /rowEntries\.map/);
  assert.doesNotMatch(panel, /entries\.slice\(\)\.reverse\(\)\.slice\(0, 6\)/);
  assert.match(panel, /if \(jobRun\.status === "succeeded"\) return \[\];/);
  assert.match(panel, /const showRuntimeState = isActiveJobRun\(jobRun\) \|\| jobRun\.status !== "succeeded";/);
  assert.doesNotMatch(panel, /slots\.slice\(-4\)/);
  // Editorial design tokens — panel chrome and chips are reused.
  assert.match(panel, /fb-panel/);
  assert.match(panel, /fb-hub-digest-meta-item/);
  assert.match(panel, /fb-chip/);
  // Relative time updater honors prefers-reduced-motion.
  assert.match(panel, /prefers-reduced-motion/);
  // Absolute timestamp is exposed via title for hover discoverability.
  assert.match(panel, /title=\{formatAbsolute\(run\.startedAt\)\}/);
});

test("DigestLogPanel renders digest status with modal-only build logs", () => {
  const panel = source("src/components/DigestLogPanel.tsx");
  const route = source("src/app/api/digest-runs/route.ts");
  const digestRuns = source("src/lib/digest-runs.ts");
  const digestUpdateStatus = source("src/lib/digest-update-status.ts");

  assert.match(route, /getCurrentSession\(\)/);
  assert.match(route, /getUserFromBearer\(request\)/);
  assert.match(route, /export async function GET\(request: Request\)/);
  assert.match(route, /const userId = session\?\.user\?\.id \?\? bearerUser\?\.id \?\? null/);
  assert.match(route, /getDigestRuns\(userId\)/);
  assert.match(route, /getScheduledAgentJobRuns\(userId, "digest-cron", 25\)/);
  assert.match(digestUpdateStatus, /@\/lib\/schedule-timing/);
  assert.match(digestUpdateStatus, /no scheduled window has completed yet/);
  assert.match(digestUpdateStatus, /No Local Agent schedule is connected/);
  assert.match(digestUpdateStatus, /No run started in the latest scheduled window/);
  assert.doesNotMatch(digestUpdateStatus, /No Local Agent schedule has reported yet|No local helper schedule has reported yet|recorded run/);
  assert.doesNotMatch(digestUpdateStatus, /first expected run has not finished yet/);
  assert.doesNotMatch(digestUpdateStatus, /function floorToExpectedSchedule/);
  assert.doesNotMatch(digestUpdateStatus, /function addScheduleInterval/);
  assert.match(panel, /AI Digest updates/);
  assert.match(panel, /showHeading = true/);
  assert.match(panel, /actionsPlacement = "end"/);
  assert.match(panel, /actionsPlacement === "start"/);
  assert.match(panel, /showHeading \|\| showStatusToggle/);
  assert.match(panel, /const showSummary = showHeading \|\| showStatusToggle/);
  assert.match(panel, /const summaryNode = showSummary \? \(/);
  assert.match(panel, /Build log/);
  assert.match(panel, /DigestLogDialog/);
  assert.match(panel, /selectedLog/);
  assert.match(panel, /const openLog = useCallback/);
  assert.match(panel, /setSelectedLog\(logRef\)/);
  assert.match(panel, /onOpenLog/);
  assert.doesNotMatch(panel, /Build status/);
  assert.doesNotMatch(panel, />\s*AI Digest build history\s*<\/h2>/);
  assert.doesNotMatch(panel, /role="tablist"/);
  assert.doesNotMatch(panel, /onKeyDown=\{handleTabKeyDown\}/);
  assert.doesNotMatch(panel, /"ArrowLeft", "ArrowRight", "Home", "End"/);
  assert.doesNotMatch(panel, /tabIndex=\{activeTab ===/);
  assert.doesNotMatch(panel, /fb-segmented-tabs/);
  assert.doesNotMatch(panel, /id="digest-update-tab-status"/);
  assert.doesNotMatch(panel, /id="digest-update-tab-log"/);
  assert.doesNotMatch(panel, /id="digest-update-panel-log"/);
  assert.doesNotMatch(panel, /role="tabpanel"/);
  assert.doesNotMatch(panel, /AI Digest build status graph/);
  assert.doesNotMatch(panel, />Digest updates<|aria-label="Digest schedule status graph"/);
  assert.match(panel, /buildDigestCronStatus/);
  assert.match(digestUpdateStatus, /const nextExpectedMs = nextExpected\.getTime\(\)/);
  assert.match(digestUpdateStatus, /nextExpectedMs > nowMs/);
  assert.match(digestUpdateStatus, /expected\.push\(nextExpected\)/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun \?\? null, "digest-cron", run\.source\)/);
  assert.match(panel, /run\.status === "synced"/);
  assert.match(panel, /postDetailHref\(item\.feedItemId, "\/dashboard\?tab=ai-digest", "AI Digest"\)/);
  assert.doesNotMatch(panel, /sync-panel-candidate-link-icon/);
  assert.doesNotMatch(panel, /aria-label="Original"/);
  assert.doesNotMatch(panel, /h-3\.5 w-3\.5/);
  assert.doesNotMatch(panel, /VISIBLE_RUN_LIMIT = 2/);
  assert.match(panel, /slotDomId/);
  assert.match(panel, /jobRunDomId/);
  assert.doesNotMatch(panel, /onOpenRun/);
  assert.doesNotMatch(panel, /setActiveTab\("log"\)/);
  assert.doesNotMatch(panel, /document\.getElementById\(runDomId\(runId\)\)/);
  assert.match(panel, /function buildDigestTimeline/);
  assert.match(panel, /matchedRunIds/);
  assert.match(panel, /matchedJobInstances/);
  assert.doesNotMatch(panel, /const LOG_WINDOW_SIZE = 6/);
  assert.match(panel, /const DIGEST_TIMELINE_LIMIT = 12/);
  assert.doesNotMatch(panel, /function visibleLogWindowStart/);
  assert.match(panel, /export function buildDigestTimeline/);
  assert.match(panel, /const jobRunFromRun = slot\.run\?\.jobRunId \? jobsByInstanceId\.get\(slot\.run\.jobRunId\) \?\? null : null/);
  assert.match(panel, /const resolvedJobRun = slot\.run \? jobRunFromRun \?\? slot\.jobRun : slot\.jobRun/);
  assert.match(panel, /if \(resolvedJobRun\) matchedJobInstances\.add\(resolvedJobRun\.instanceId\)/);
  assert.match(panel, /const rowEntries = useMemo\(\(\) => entries\.slice\(\)\.reverse\(\), \[entries\]\)/);
  assert.match(panel, /const hasScrollCue = rowEntries\.length > 3/);
  assert.doesNotMatch(panel, /const visibleRowEntries = rowEntries\.slice\(logWindowStart, logWindowStart \+ LOG_WINDOW_SIZE\)/);
  assert.doesNotMatch(panel, /visibleGraphEntries\.map/);
  assert.match(panel, /className=\{`sync-panel-scroll-cue\$\{hasScrollCue \? " has-more" : ""\}`\}/);
  assert.match(panel, /className="sync-panel-slot-rows is-scrollable is-timeline"/);
  assert.match(panel, /data-sync-log-row="true"/);
  assert.doesNotMatch(panel, /className="sync-panel-timeline-divider" aria-hidden="true"/);
  assert.doesNotMatch(panel, /Last \{visibleCount\} AI Digest/);
  assert.doesNotMatch(panel, /className="sync-panel-timeline-axis"/);
  assert.doesNotMatch(panel, /visibleGraphEntries|graphStartLabel|graphEndLabel/);
  assert.doesNotMatch(panel, />Oldest</);
  assert.doesNotMatch(panel, />Newest</);
  assert.match(source("src/lib/scheduled-window-ui.ts"), /No run yet/);
  assert.doesNotMatch(panel, /No AI Digest schedule has reported yet/);
  assert.match(panel, /Copy a Build AI Digest prompt to start a Local Agent run/);
  assert.doesNotMatch(panel, /Use Build AI Digest to copy a Local Agent prompt/);
  assert.match(panel, /No AI Digest build history yet/);
  assert.match(panel, /Copy a Build AI Digest prompt to create history/);
  assert.doesNotMatch(panel, /No AI Digest builds yet|Started one-time and scheduled builds appear here|One-time and scheduled builds appear here after they start|One-time and scheduled AI Digest builds appear here|Scheduled and one-time AI Digest builds will appear here|after a Local Agent reports them/);
  assert.match(panel, /No AI Digest was saved for this run/);
  assert.match(panel, /@\/lib\/scheduled-window-ui/);
  assert.match(panel, /scheduledWindowStatusLabel/);
  assert.match(panel, /scheduledWindowStyleStatus/);
  assert.match(panel, /scheduledWindowRunNote/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun, "digest-cron"\)/);
  assert.match(panel, /scheduledRunTriggerLabel\(jobRun \?\? null, "digest-cron", run\.source\)/);
  assert.match(panel, /const noUpdate = isNoUpdateDigestRun\(entry\.run, entry\.jobRun\);/);
  assert.match(panel, /jobRunByInstanceId/);
  assert.match(panel, /<RunCard domId=\{null\} jobRun=\{jobRun \?\? undefined\} run=\{run\} suppressStalled=\{suppressStalled\} \/>/);
  assert.match(panel, /AI Digest job lifecycle/);
  assert.match(panel, /function isStalledDigestJobRun/);
  assert.match(panel, /function isNoUpdateDigestRun/);
  assert.match(panel, /\? "No update"[\s\S]*scheduledWindowStatusLabel\(entry\.status\)/);
  assert.match(panel, /if \(isStalledDigestJobRun\(jobRun, nowMs, stallGraceUntilMs\)\) return "stalled"/);
  assert.match(panel, /LIVE_LOG_STALL_GRACE_MS = 10_000/);
  assert.match(panel, /setLiveLogSuppressStalled\(true\)/);
  assert.match(panel, /refresh\(\)/);
  assert.match(panel, /suppressStalled=\{liveLogSuppressStalled\}/);
  assert.match(panel, /if \(isStalledDigestJobRun\(jobRun, nowMs, stallGraceUntilMs\)\) return "Stalled"/);
  assert.match(panel, /function hasTerminalFailedDigestJob/);
  assert.match(panel, /if \(hasTerminalFailedDigestJob\(jobRun\)\) return "failed";[\s\S]*if \(run\.status === "synced"\) return "ok";/);
  assert.match(digestUpdateStatus, /function digestSlotStatusForRun/);
  assert.match(digestUpdateStatus, /if \(run\.status === "synced"\) return "ok";/);
  assert.match(panel, /Local Agent stopped reporting before the AI Digest was saved\./);
  assert.match(panel, /Prepare candidates/);
  assert.match(panel, /Run Local Agent/);
  assert.match(panel, /Render digest JSON/);
  assert.match(panel, /Save to FollowBrief/);
  assert.match(panel, /Record digested posts/);
  assert.doesNotMatch(panel, /No saved title/);
  assert.match(panel, /jobRunVerdict/);
  assert.match(panel, /jobRunDiagnostic/);
  assert.match(panel, /function jobRunDisplaySummary/);
  assert.match(panel, /\^runtime heartbeat\\\.\?\$/);
  assert.match(panel, /Local Agent is working on this AI Digest\./);
  assert.match(panel, /const showRuntimeState = !activeJob && jobRun\.status !== "succeeded" && Boolean\(jobRun\.stage\);/);
  assert.match(panel, /const showFailureDetails = !activeJob && jobRun\.status !== "succeeded"/);
  assert.doesNotMatch(panel, /\{jobRun\.stage \|\| "runtime"\} · \{jobRun\.finishedAt \? "finished" : "active"\}/);
  assert.match(panel, /digestRunVerdict/);
  assert.match(panel, /text: "No update\. No new eligible posts in this window\."/);
  assert.match(panel, /jobRunFailureReason/);
  assert.match(panel, /readableReason/);
  assert.match(panel, /Timed out after \$\{formatCount\(timeoutSeconds\)\} seconds/);
  assert.match(panel, /Local Agent is preparing candidates and saving the AI Digest/);
  assert.match(panel, /Local Agent finished without saving an AI Digest/);
  assert.match(panel, /Saved \$\{formatCount\(run\.includedCount \?\? 0\)\} of \$\{formatCount\(run\.candidateCount\)\} posts, but Local Agent marked the run failed/);
  assert.match(panel, /Prepared \$\{formatCount\(run\.candidateCount\)\} candidates\. Local Agent stopped before saving/);
  assert.match(panel, /Waiting for Local Agent to save the AI Digest/);
  assert.match(panel, /Saved \$\{formatCount\(run\.includedCount \?\? 0\)\} of \$\{formatCount\(run\.candidateCount\)\} eligible posts to FollowBrief/);
  assert.match(panel, /DigestLifecycle/);
  assert.match(panel, /function hasFailedDigestJob/);
  assert.match(panel, /statusChip\(run, jobRun, stallGraceUntilMs\)/);
  assert.match(panel, /label: jobRun \? jobRunStatusLabel\(jobRun, undefined, stallGraceUntilMs\) : "Failed"/);
  assert.match(panel, /runtime failed/);
  assert.match(panel, /sync-panel-mobile-flat/);
  assert.match(panel, /className="sync-panel-run-card sync-panel-mobile-flat"/);
  assert.doesNotMatch(panel, /No digest schedule has reported yet|No digest builds yet|prepares a digest|digest build record|The Local Agent is running|Waiting for the Local Agent to save AI Digest|Runtime job did not create/);
  assert.match(panel, /Open log/);
  assert.match(panel, /className="sync-panel-title-row"/);
  assert.match(panel, /className="sync-panel-error"/);
  assert.match(source("src/components/DigestLogPanel.tsx"), /if \(response\.status === 401\) \{[\s\S]*setError\(null\);[\s\S]*return;[\s\S]*\}/);
  assert.match(panel, /className="sync-panel-run-card sync-panel-mobile-flat"/);
  assert.match(panel, /className="sync-panel-run-card-head"/);
  assert.match(panel, /className="sync-panel-run-card-summary"/);
  assert.match(panel, /className="sync-panel-run-card-title"/);
  assert.match(panel, /<p className="sync-panel-run-card-title">\{title\}<\/p>[\s\S]*<header className="sync-panel-run-card-head">/);
  assert.match(panel, /className=\{`sync-panel-run-card-verdict is-\$\{verdict\.tone\}`\}/);
  assert.match(panel, /className="sync-panel-run-card-reason"/);
  assert.match(source("src/app/globals.css"), /\.sync-panel-run-card-verdict\s*{/);
  assert.match(source("src/app/globals.css"), /\.sync-panel-run-card-verdict\.is-fail\s*{/);
  assert.match(source("src/app/globals.css"), /\.sync-panel-run-card-reason\s*{/);
  assert.match(panel, /className="sync-panel-run-card-funnel"/);
  assert.match(panel, /className="sync-panel-run-card-details"/);
  assert.match(panel, /className="sync-panel-schedule-summary"/);
  assert.match(panel, /className="sync-panel-column"/);
  assert.match(panel, /className="sync-panel-truncate"/);
  assert.match(panel, /className="sync-panel-status-brief"/);
  assert.match(panel, /className="sync-panel-layout is-log-only"/);
  assert.match(panel, /<dt>Schedule enabled<\/dt>/);
  assert.doesNotMatch(panel, /<dt>Next scheduled run<\/dt>/);
  assert.match(panel, /<dt>Runner<\/dt>/);
  assert.doesNotMatch(panel, /className=\{`sync-panel-slot-bar \$\{heightClass\}`\}/);
  assert.match(panel, /className="sync-panel-slot-row"/);
  assert.match(panel, /className="sync-panel-slot-row-main"/);
  assert.match(panel, /className="sync-panel-slot-row-primary"/);
  assert.match(panel, /className="sync-panel-slot-row-secondary"/);
  assert.match(panel, /className="sync-panel-slot-row-side"/);
  assert.match(panel, /className=\{`sync-panel-slot-row-status \$\{toneClass\(displayTone\)\}`\}/);
  assert.match(panel, /className="sync-panel-slot-row-dot"/);
  assert.doesNotMatch(panel, /style=\{\{ color: style\.color \}\}/);
  assert.doesNotMatch(panel, /style=\{\{ background: style\.color \}\}/);
  assert.match(panel, /className="sync-panel-slot-row-kind"/);
  assert.match(panel, /className="sync-panel-slot-row-time"/);
  assert.match(panel, /className="mono sync-panel-slot-row-note"/);
  assert.match(panel, /\{entry\.syncSummary \? \(/);
  assert.match(panel, /\{entry\.syncSummary\}<\/span>/);
  assert.doesNotMatch(panel, /\{entry\.note\}<\/span>/);
  assert.doesNotMatch(panel, /sync-panel-chip-row/);
  assert.doesNotMatch(panel, /rebuilds past posts/);
  assert.doesNotMatch(panel, /one-time only/);
  assert.doesNotMatch(panel, /slice\(0, 6\)/);
  assert.match(panel, /className="sync-panel-funnel-arrow"/);
  assert.match(panel, /className="sync-panel-funnel-stat"/);
  assert.match(panel, /className=\{`mono sync-panel-funnel-stat-value\$\{tone \? ` is-\$\{tone\}` : ""\}`\}/);
  assert.match(panel, /className="sync-panel-funnel-stat-label"/);
  assert.match(panel, /className="sync-panel-run-card-detail-heading"/);
  assert.match(panel, /className="sync-panel-run-card-source-list"/);
  assert.match(panel, /className="sync-panel-run-card-candidate-list"/);
  assert.match(panel, /const VISIBLE_CANDIDATE_LIMIT = 4/);
  assert.match(panel, /const visibleCandidates = postsExpanded \? run\.candidates : run\.candidates\.slice\(0, VISIBLE_CANDIDATE_LIMIT\)/);
  assert.match(panel, /CountMeta label="more posts" value=\{hiddenCandidateCount\}/);
  assert.match(panel, /CountMeta label="more sources with new posts" value=\{hiddenSourceCount\}/);
  assert.match(panel, /href=\{`\/builder\/\$\{src\.entityId\}`\}/);
  assert.match(panel, /className="sync-panel-source-row"/);
  assert.match(panel, /className="sync-panel-candidate-row"/);
  assert.match(panel, /className=\{`mono sync-panel-candidate-outcome is-\$\{outcomeTone\}`\}/);
  assert.match(panel, /className="mono sync-panel-candidate-kind"/);
  assert.match(panel, /not used/);
  assert.match(panel, /pending/);
  assert.match(panel, /Sources and posts considered/);
  assert.match(panel, /Source coverage/);
  assert.match(panel, /Posts considered/);
  assert.match(panel, /sync-panel-candidate-title/);
  assert.doesNotMatch(panel, /sync-panel-candidate-source/);
  assert.match(digestRuns, /prisma\.feedItem\.findMany/);
  assert.match(digestRuns, /select: \{ id: true, title: true, body: true \}/);
  assert.match(digestRuns, /function candidateTitle/);
  assert.match(digestRuns, /const snapshotTitle = snapshot\.title\?\.trim\(\)/);
  assert.match(digestRuns, /const feedItemTitle = feedItem\?\.title\?\.trim\(\)/);
  assert.match(digestRuns, /firstBodyLine\(feedItem\.body\)/);
  assert.doesNotMatch(panel, /className="rounded-\[10px\] border bg-\[var\(--paper-strong\)\] px-3\.5 py-3"[\s\S]*Runtime job did not create an AI Digest build record/);
  assert.doesNotMatch(panel, /className="rounded-\[10px\] border bg-\[var\(--paper-strong\)\] px-3\.5 py-3"[\s\S]*Previous AI Digest/);
  assert.doesNotMatch(panel, /className="flex items-baseline justify-between gap-2 text-\[12px\]"/);
  assert.doesNotMatch(panel, /className="flex items-start gap-2 text-\[12\.5px\] leading-snug"/);
  assert.doesNotMatch(panel, /className="mono mt-\[1px\] w-\[2\.6em\] shrink-0 text-\[10px\]/);
  assert.doesNotMatch(panel, /className="mt-1\.5 text-\[13px\] leading-relaxed text-\[var\(--muted-strong\)\]"/);
  assert.doesNotMatch(panel, /className="flex flex-wrap items-center justify-between gap-2 rounded-\[7px\] px-1 py-1 text-\[12\.5px\] target:bg-\[var\(--accent-soft\)\]"/);
  assert.doesNotMatch(panel, /focus-visible:outline-\[var\(--accent\)\]/);
  assert.doesNotMatch(panel, /className="inline-flex items-baseline gap-1"/);
  assert.doesNotMatch(panel, /digest-updates-head[\s\S]{0,360}flex flex-wrap items-center gap-2/);
  assert.doesNotMatch(panel, /error \? \([\s\S]{0,120}mt-3 text-\[12px\] text-\[var\(--danger\)\]/);
  assert.doesNotMatch(panel, /slots\.slice\(-4\)/);
  assert.doesNotMatch(panel, /RefreshCw/);
  assert.doesNotMatch(panel, />Refresh</);
  assert.match(route, /cronRuns/);
  assert.match(route, /digestCronJob\.findUnique/);
  assert.match(route, /serializeDigestCronJob/);
  assert.match(digestRuns, /export type DigestCronJobStatus/);
  assert.match(digestRuns, /source\?: string/);
  assert.match(digestRuns, /serializeDigestCronJob/);
});

test("builders page mounts the fetch log inside the sync header section", () => {
  const buildersPage = source("src/app/(workspace)/builders/page.tsx");
  assert.match(buildersPage, /FetchLogPanel/);
  // Fetch the user's recent runs server-side, ordered by startedAt desc.
  assert.match(buildersPage, /prisma\.libraryFetchRun\.findMany/);
  assert.match(buildersPage, /prisma\.libraryCronJob\.findUnique/);
  assert.match(buildersPage, /source: "cron"/);
  assert.match(buildersPage, /orderBy: \{ startedAt: "desc" \}/);
  assert.match(buildersPage, /const FETCH_RUN_PAGE_SIZE = 10/);
  assert.match(buildersPage, /const FETCH_RUN_QUERY_SIZE = FETCH_RUN_PAGE_SIZE \+ 1/);
  assert.match(buildersPage, /take: FETCH_RUN_QUERY_SIZE/);
  assert.match(buildersPage, /rawFetchRuns\.slice\(0, FETCH_RUN_PAGE_SIZE\)\.map/);
  // Mounted with the user's own library controls so Fetch setup stays together.
  assert.match(buildersPage, /<Suspense fallback=\{<FetchSourcesFallback \/>/);
  assert.match(buildersPage, /function FetchSourcesFallback/);
  assert.match(buildersPage, /className="your-library-panel library-section-panel"/);
  assert.match(buildersPage, /actions=\{/);
  assert.match(buildersPage, /compactOnly/);
  assert.match(buildersPage, /activeSchedule=\{data\.libraryCronJob\}/);
  assert.match(buildersPage, /showStop=\{showStopLibraryCron\}/);
  assert.match(buildersPage, /libraryCronJob\?\.status === "active"/);
  assert.match(buildersPage, /initialCronJob=\{data\.libraryCronJob\}/);
  assert.match(buildersPage, /initialCronRuns=\{data\.cronRuns\}/);
  assert.match(buildersPage, /initialRuns=\{data\.fetchRuns\}/);
  assert.match(buildersPage, /summaryLanguage=\{data\.summaryLanguage\}/);
  assert.match(buildersPage, /<OwnDigestPipelineUpdatesCard/);
  assert.match(buildersPage, /context="digest"/);
  assert.match(buildersPage, /activeSchedule=\{data\.digestCronJob\}/);
  assert.match(buildersPage, /showStop=\{showStopDigestCron\}/);
  assert.match(buildersPage, /initialCronJob=\{data\.digestCronJob\}/);
  assert.match(buildersPage, /initialCronRuns=\{data\.digestCronRuns\}/);
  assert.match(buildersPage, /initialRuns=\{data\.digestRuns\}/);
});
