import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const root = process.cwd();

function source(path: string) {
  return readFileSync(join(root, path), "utf8");
}

function optionalSource(path: string) {
  return existsSync(join(root, path)) ? source(path) : "";
}

test("primary app navigation keeps route prefetching enabled", () => {
  const appNav = source("src/components/AppNav.tsx");

  assert.equal(appNav.includes("prefetch={false}"), false);
});

test("app shell reuses the page session instead of fetching it again", () => {
  const appShell = source("src/components/AppShell.tsx");
  const workspaceLayout = source("src/app/(workspace)/layout.tsx");

  assert.equal(appShell.includes("getServerSession"), false);
  assert.match(appShell, /session\??:/);
  assert.match(workspaceLayout, /<AppShell session=\{session\}>/);
  for (const pagePath of [
    "src/app/(workspace)/dashboard/page.tsx",
    "src/app/(workspace)/builders/page.tsx",
    "src/app/(workspace)/library-hub/page.tsx",
    "src/app/(workspace)/search/page.tsx",
    "src/app/(workspace)/settings/page.tsx",
  ]) {
    assert.doesNotMatch(source(pagePath), /AppShell/);
  }
});

test("public entry pages use the centered product layout", () => {
  const landingPage = source("src/app/page.tsx");
  const loginPage = source("src/app/login/page.tsx");
  const globals = source("src/app/globals.css");

  assert.match(landingPage, /fb-public-nav/);
  assert.match(landingPage, /fb-public-section fb-public-hero/);
  assert.match(landingPage, /fb-public-title/);
  assert.match(landingPage, /fb-public-copy/);
  assert.match(landingPage, /fb-public-actions/);
  assert.match(landingPage, /fb-public-metrics/);
  assert.match(landingPage, /fb-public-nav-actions/);
  assert.match(landingPage, /fb-product-preview-head/);
  assert.match(landingPage, /fb-product-preview-title-row/);
  assert.match(landingPage, /fb-product-preview-list/);
  assert.match(landingPage, /fb-signal-copy/);
  assert.match(landingPage, /fb-signal-title/);
  assert.match(landingPage, /fb-signal-desc/);
  assert.match(landingPage, /fb-public-section-kicker-row/);
  assert.match(landingPage, /fb-public-workflow/);
  assert.match(landingPage, /fb-public-step-card-head/);
  assert.match(landingPage, /fb-public-card-copy/);
  assert.match(landingPage, /fb-public-workspace/);
  assert.match(landingPage, /fb-public-feature-grid/);
  assert.match(landingPage, /fb-public-metric/);
  assert.doesNotMatch(landingPage, /max-w-7xl/);
  assert.doesNotMatch(landingPage, /mt-6 max-w-xl/);
  assert.doesNotMatch(landingPage, /serif text-5xl/);
  assert.doesNotMatch(landingPage, /className="flex items-center/);
  assert.doesNotMatch(landingPage, /className="grid gap/);
  assert.doesNotMatch(landingPage, /className="mt-/);
  assert.doesNotMatch(landingPage, /className="rounded-lg border/);
  assert.match(loginPage, /fb-login-shell/);
  assert.match(loginPage, /fb-login-title/);
  assert.match(loginPage, /fb-login-copy/);
  assert.match(loginPage, /fb-login-proof-grid/);
  assert.match(loginPage, /fb-login-panel-copy/);
  assert.match(loginPage, /fb-login-brand-row/);
  assert.match(loginPage, /fb-login-brand-name/);
  assert.match(loginPage, /fb-login-panel-head/);
  assert.match(loginPage, /fb-login-panel-icon/);
  assert.match(loginPage, /fb-dark-proof-icon/);
  assert.match(loginPage, /fb-dark-proof-label/);
  assert.doesNotMatch(loginPage, /max-w-6xl/);
  assert.doesNotMatch(loginPage, /lg:max-w-md/);
  assert.doesNotMatch(loginPage, /mt-5 max-w-lg/);
  assert.doesNotMatch(loginPage, /className="flex items-/);
  assert.doesNotMatch(loginPage, /className="rounded-lg/);
  assert.doesNotMatch(loginPage, /className="mt-/);
  assert.match(globals, /\.fb-public-nav,[\s\S]*\.fb-public-section\s*{[\s\S]*max-width:\s*var\(--workspace-max\)/);
  assert.match(globals, /\.fb-public-hero\s*{[\s\S]*grid-template-columns:/);
  assert.match(globals, /\.fb-product-preview-head\s*{[\s\S]*border-bottom:\s*1px solid var\(--line\)/);
  assert.match(globals, /\.fb-public-workspace\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*0\.9fr\) minmax\(0,\s*1\.1fr\)/);
  assert.match(globals, /@media \(max-width:\s*767px\)[\s\S]*\.fb-public-feature-grid\s*{[\s\S]*grid-template-columns:\s*1fr/);
  assert.match(globals, /\.fb-login-brand-row\s*{[\s\S]*display:\s*flex/);
  assert.match(globals, /\.fb-login-panel-head\s*{[\s\S]*justify-content:\s*space-between/);
  assert.match(globals, /\.fb-public-copy\s*{[\s\S]*max-width:\s*36rem/);
  assert.match(globals, /\.fb-login-shell\s*{[\s\S]*max-width:\s*var\(--workspace-max\)/);
  assert.match(globals, /\.fb-login-copy\s*{[\s\S]*max-width:\s*32rem/);
  assert.match(globals, /\.fb-dark-panel\s*{[\s\S]*max-width:\s*28rem/);
  assert.doesNotMatch(globals, /\.landing-grid\s*{/);
  assert.doesNotMatch(globals, /\.app-topbar\s*{/);
  assert.doesNotMatch(globals, /\.page-header\s*{/);
});

test("settings live in the clickable user avatar menu", () => {
  const appShell = source("src/components/AppShell.tsx");
  const appNav = source("src/components/AppNav.tsx");
  const settingsPage = source("src/app/(workspace)/settings/page.tsx");
  const globals = source("src/app/globals.css");
  const userMenu = source("src/components/UserMenu.tsx");
  const agentTokenPanel = source("src/components/AgentTokenPanel.tsx");
  const fetchLogPanel = source("src/components/FetchLogPanel.tsx");
  const skillPromptActions = source("src/components/SkillPromptActions.tsx");
  const digestDetails = source("src/components/DigestDetails.tsx");
  const adminDigestConfig = source("src/components/AdminDigestConfigForm.tsx");
  const adminSourceTypeManager = source("src/components/AdminSourceTypeManager.tsx");
  const settingsFields = source("src/components/settings/SettingsFields.tsx");
  const markdownEditor = source("src/components/settings/MarkdownEditor.tsx");
  const commonRulesForm = source("src/components/CommonSummaryRulesForm.tsx");

  assert.doesNotMatch(appShell, /label: "Agent"/);
  assert.doesNotMatch(appNav, /"key"/);
  assert.match(appShell, /@\/components\/UserMenu/);
  assert.match(userMenu, /"use client"/);
  assert.match(userMenu, /className="user-menu-trigger"/);
  assert.match(userMenu, /aria-label=\{email \? `Account menu for \$\{email\}` : `Account menu for \$\{name\}`\}/);
  assert.match(userMenu, /detailsRef\.current\.open = false/);
  assert.match(userMenu, /themeHydrated/);
  assert.match(agentTokenPanel, /timeZone:\s*"UTC"/);
  assert.match(fetchLogPanel, /startedAtLabel = hydrated \? formatRelative/);
  assert.match(skillPromptActions, /!\s*open \? null/);
  assert.match(digestDetails, /useHydrated/);
  // Timestamp formatting now lives in the shared settings field module; both
  // admin forms render UTC timestamps through it.
  assert.match(settingsFields, /formatUtcDateTime/);
  assert.match(settingsFields, /timeZone:\s*"UTC"/);
  assert.match(settingsFields, /optional\?: boolean/);
  assert.match(settingsFields, /placeholder\?: string/);
  assert.match(settingsFields, /OptionalBadge/);
  assert.match(settingsFields, /className="settings-section-head"/);
  assert.match(settingsFields, /className="settings-section-title-row"/);
  assert.match(settingsFields, /className="settings-field-label"/);
  assert.match(settingsFields, /className="settings-field-help"/);
  assert.match(settingsFields, /className="settings-choice-list"/);
  assert.match(settingsFields, /className="settings-footer-bar"/);
  assert.match(settingsFields, /className="settings-save-status is-saved"/);
  assert.doesNotMatch(settingsFields, /style=\{\{/);
  assert.doesNotMatch(settingsFields, /className="settings-section mt-7/);
  assert.doesNotMatch(settingsFields, /className="settings-field block text-sm/);
  assert.match(adminDigestConfig, /FooterBar/);
  assert.match(adminDigestConfig, /@\/components\/settings\/SettingsFields/);
  assert.match(adminDigestConfig, /HEADLINE_PROMPT_PLACEHOLDER/);
  assert.match(adminDigestConfig, /PER_SOURCE_SUMMARY_PROMPT_PLACEHOLDER/);
  assert.match(adminDigestConfig, /headlinePrompt/);
  assert.match(adminDigestConfig, /perSourceSummaryPrompt/);
  assert.doesNotMatch(adminDigestConfig, /OrderedChoiceField/);
  assert.match(adminDigestConfig, /TRANSLATE_PROMPT_PLACEHOLDER/);
  assert.match(adminSourceTypeManager, /@\/components\/settings\/SettingsFields/);
  assert.match(adminSourceTypeManager, /FETCH_PROMPT_PLACEHOLDER/);
  assert.match(adminSourceTypeManager, /SUMMARY_PROMPT_PLACEHOLDER/);
  assert.match(adminSourceTypeManager, /placeholder="Example: 200"/);
  assert.match(adminSourceTypeManager, /placeholder="Example: 0\.35"/);
  assert.match(adminSourceTypeManager, /<OptionalMarkdownField/);
  assert.match(adminSourceTypeManager, /buttonLabel="Add fetch prompt"/);
  assert.match(adminSourceTypeManager, /canEditQualityGates \? \(/);
  assert.match(settingsPage, /canEditQualityGates=\{isAdmin\}/);
  assert.match(commonRulesForm, /placeholder=\{\[/);
  assert.match(markdownEditor, /placeholder\?: string/);
  assert.match(markdownEditor, /placeholder=\{placeholder\}/);
  assert.match(globals, /\.settings-optional-badge/);
  assert.match(globals, /\.settings-optional-empty/);
  assert.match(globals, /\.settings-section-head\s*{[\s\S]*border-bottom:\s*1px solid var\(--line\)/);
  assert.match(globals, /\.settings-field-label\s*{[\s\S]*text-transform:\s*uppercase/);
  assert.match(globals, /\.settings-token-add-row\s*{[\s\S]*display:\s*flex/);
  assert.match(globals, /\.settings-footer-bar\s*{[\s\S]*border-top:\s*1px solid var\(--line\)/);
  assert.match(globals, /\.fb-input::placeholder/);
  assert.match(globals, /\.settings-markdown-textarea::placeholder/);
  assert.match(userMenu, /href="\/settings" onClick=\{closeMenu\}[\s\S]*Settings/);
  assert.match(userMenu, /signOut\(\{ callbackUrl: "\/login" \}\)/);
  assert.match(userMenu, /closeMenu\(\);[\s\S]*signOut\(\{ callbackUrl: "\/login" \}\)[\s\S]*Sign out/);
  assert.match(settingsPage, />\s*Settings\s*</);
  assert.equal(existsSync(join(root, "src/app/(workspace)/settings/loading.tsx")), false);
  assert.doesNotMatch(settingsPage, /ActiveTokenChip/);
  assert.match(settingsPage, /<Suspense fallback=\{<AgentTokenPanelSkeleton \/>/);
  assert.doesNotMatch(settingsPage, /Agent login/);
  assert.match(globals, /\.user-avatar/);
  assert.match(globals, /\.user-menu-popover/);
});

test("desktop shell uses centered top navigation and merged home feeds", () => {
  const appShell = source("src/components/AppShell.tsx");
  const appNav = source("src/components/AppNav.tsx");
  const dashboardPage = source("src/app/(workspace)/dashboard/page.tsx");
  const dashboardTabs = source("src/components/DashboardHomeTabs.tsx");
  const builderDetailPage = source("src/app/(workspace)/builder/[entityId]/page.tsx");
  const rootLoading = source("src/app/loading.tsx");
  const routeLoading = source("src/components/RouteLoading.tsx");
  const searchForm = source("src/components/SearchForm.tsx");
  const digestDetails = source("src/components/DigestDetails.tsx");
  const recommendationsPage = source("src/app/(workspace)/recommendations/page.tsx");
  const globals = source("src/app/globals.css");

  assert.match(appShell, /label: "Home"/);
  assert.doesNotMatch(appShell, /label: "Digest"/);
  assert.doesNotMatch(appShell, /label: "For You"/);
  assert.doesNotMatch(appShell, /label: "History"/);
  assert.match(appShell, /aria-label="Search"/);
  assert.doesNotMatch(appNav, /recommendations/);
  assert.match(appNav, /"search"/);
  assert.match(appShell, /className="fb-top /);
  assert.match(appShell, /className="fb-top-inner"/);
  assert.match(appShell, /desktopLayout="bar"/);
  assert.match(appShell, /className="app-main"/);
  assert.doesNotMatch(appShell, /<aside/);
  assert.match(appShell, /<SearchForm query="" variant="header" \/>/);
  assert.match(searchForm, /name="q"/);
  assert.match(appNav, /desktopLayout = "rail"/);
  assert.match(appNav, /fb-nav-list-bar/);
  assert.match(appNav, /fb-nav-list-rail/);
  assert.match(dashboardPage, /className="fb-page-head"/);
  assert.match(dashboardPage, /<h1 className="fb-title">Home<\/h1>/);
  assert.match(dashboardPage, /Read your AI Digest, saved posts, and followed-source updates/);
  assert.doesNotMatch(dashboardPage, /<h1 className="sr-only">Home<\/h1>/);
  assert.match(dashboardPage, /className="home-workspace"/);
  assert.match(dashboardPage, /className="ai-digest-stack"/);
  assert.match(dashboardPage, /className="digest-source-selector"/);
  assert.match(dashboardPage, /className="digest-source-list"/);
  assert.match(dashboardPage, /className="ai-digest-empty"/);
  assert.match(dashboardPage, /className="ai-digest-empty-inner"/);
  assert.doesNotMatch(dashboardPage, /className="grid gap-5"/);
  assert.doesNotMatch(dashboardPage, /aria-label="Digest source" className="mt-4"/);
  assert.doesNotMatch(dashboardPage, /className="fb-panel dashed"/);
  assert.match(dashboardPage, /DashboardHomeTabs/);
  assert.match(dashboardTabs, /role="tablist"/);
  assert.match(globals, /\.fb-segmented-tabs/);
  assert.match(globals, /\.fb-segmented-tabs \.fb-btn\[aria-selected="true"\]/);
  assert.match(dashboardTabs, /useState\(initialTab\)/);
  assert.doesNotMatch(dashboardTabs, /useSearchParams/);
  assert.match(dashboardTabs, /router\.replace/);
  assert.doesNotMatch(dashboardTabs, /window\.history\.pushState/);
  assert.doesNotMatch(dashboardTabs, /router\.push/);
  assert.doesNotMatch(dashboardTabs, /<Link/);
  assert.match(dashboardTabs, /Digest/);
  assert.match(dashboardTabs, /ai-digest/);
  assert.match(dashboardTabs, /Digest[\s\S]*Favorites[\s\S]*Following/);
  assert.doesNotMatch(dashboardTabs, /For You/);
  assert.match(dashboardTabs, /\{ id: "ai-digest", label: "Digest" \}[\s\S]*\{ id: "favorites", label: "Favorites" \}[\s\S]*\{ id: "subscription", label: "Following" \}/);
  assert.doesNotMatch(dashboardPage, /scope="subscription"/);
  assert.doesNotMatch(dashboardPage, /scope="for-you"/);
  assert.doesNotMatch(dashboardPage, /<h3>Status<\/h3>/);
  assert.doesNotMatch(dashboardPage, /HomeStatsSlot/);
  assert.doesNotMatch(dashboardPage, /fb-rail/);
  assert.doesNotMatch(dashboardPage, /Manage sources/);
  assert.doesNotMatch(dashboardPage, /Recent digest/);
  assert.match(dashboardPage, /Digest archive/);
  assert.match(dashboardPage, /FavoritePostsSection/);
  assert.match(dashboardPage, /FollowingRecommendationSection/);
  assert.doesNotMatch(dashboardPage, /getRecommendationTimeline/);
  assert.match(digestDetails, /mode === "today"/);
  assert.match(recommendationsPage, /redirect\("\/dashboard\?tab=subscription"\)/);
  assert.match(builderDetailPage, /className="builder-detail-workspace"/);
  assert.match(builderDetailPage, /className="builder-detail-head-stack"/);
  assert.match(builderDetailPage, /className="builder-detail-identity"/);
  assert.match(builderDetailPage, /className="builder-detail-avatar"/);
  assert.match(builderDetailPage, /className="builder-detail-title-stack"/);
  assert.match(builderDetailPage, /className="builder-detail-title-row"/);
  assert.match(builderDetailPage, /className="builder-detail-host source-host-meta mono truncate"/);
  assert.match(builderDetailPage, /className="builder-detail-bio fb-desc"/);
  assert.match(builderDetailPage, /className="builder-detail-actions-skeleton"/);
  assert.match(builderDetailPage, /className="builder-detail-action-skeleton-button"/);
  assert.match(builderDetailPage, /className="builder-detail-channel-list"/);
  assert.match(builderDetailPage, /className="builder-detail-channel-row"/);
  assert.match(builderDetailPage, /className="recent-post-list recent-post-list--skeleton"/);
  assert.match(builderDetailPage, /className="recent-post-skeleton-card fb-panel"/);
  assert.match(builderDetailPage, /className="recent-post-skeleton-line recent-post-skeleton-line--meta"/);
  assert.match(builderDetailPage, /className="recent-post-skeleton-line recent-post-skeleton-line--title"/);
  assert.doesNotMatch(builderDetailPage, /<SourceAvatar[\s\S]*style=\{\{/);
  assert.doesNotMatch(builderDetailPage, /bg-black\/10|className="h-|animate-pulse rounded/);
  assert.doesNotMatch(builderDetailPage, /className="grid gap-3"/);
  assert.doesNotMatch(builderDetailPage, /className="mt-3 grid gap-2"/);
  assert.doesNotMatch(builderDetailPage, /md:grid-cols-\[1fr_auto_auto\]/);
  assert.doesNotMatch(builderDetailPage, /className="grid gap-4" aria-busy/);
  assert.doesNotMatch(builderDetailPage, /mt-8 grid gap-6/);
  assert.doesNotMatch(builderDetailPage, /fb-panel dashed mt-10/);
  assert.match(globals, /--workspace-max:\s*72rem/);
  assert.match(globals, /\.page-pad\s*{[\s\S]*margin-inline:\s*auto/);
  assert.match(globals, /\.page-pad\s*{[\s\S]*width:\s*min\(100%,\s*var\(--workspace-max\)\)/);
  assert.match(globals, /\.workspace-content-stack\s*{[\s\S]*margin-top:\s*clamp/);
  assert.match(globals, /\.builder-detail-action-skeleton-button\s*{[\s\S]*border-radius:\s*999px/);
  assert.match(globals, /\.recent-post-skeleton-line--title\s*{[\s\S]*width:\s*min\(75%,\s*32rem\)/);
  assert.match(rootLoading, /className="workspace-content-stack"/);
  assert.match(rootLoading, /className="fb-page-head"/);
  assert.doesNotMatch(rootLoading, /space-y-7/);
  assert.match(routeLoading, /className="workspace-content-stack"/);
  assert.match(routeLoading, /className="route-loading-title"/);
  assert.match(routeLoading, /className="route-loading-desc"/);
  assert.match(routeLoading, /className="route-loading-chip"/);
  assert.match(routeLoading, /className="route-loading-list"/);
  assert.match(routeLoading, /className="route-loading-row"/);
  assert.doesNotMatch(routeLoading, /item-list mt-6/);
  assert.doesNotMatch(routeLoading, /bg-black\/10/);
  assert.doesNotMatch(routeLoading, /className="h-/);
  assert.match(globals, /\.fb-top\s*{[\s\S]*position:\s*sticky/);
  assert.match(globals, /\.fb-top-inner\s*{[\s\S]*width:\s*min\(100%,\s*var\(--workspace-max\)\)/);
  assert.match(globals, /\.fb-page-head\s*{[\s\S]*border-bottom:/);
  assert.match(globals, /\.route-loading-title\s*{[\s\S]*height:\s*1\.75rem/);
  assert.match(globals, /\.route-loading-list\s*{[\s\S]*display:\s*grid/);
  assert.doesNotMatch(globals, /\.home-rail/);
  assert.doesNotMatch(globals, /\.home-main/);
  assert.doesNotMatch(globals, /\.home-tabs/);
  assert.match(globals, /\.home-workspace\s*{[\s\S]*min-width:\s*0/);
  assert.match(globals, /\.ai-digest-stack\s*{[\s\S]*display:\s*grid/);
  assert.match(globals, /\.digest-source-list\s*{[\s\S]*flex-wrap:\s*wrap/);
  assert.match(globals, /\.ai-digest-empty\s*{[\s\S]*border:\s*1px dashed var\(--line\)/);
  assert.match(globals, /@media \(max-width:\s*767px\)[\s\S]*\.digest-source-list\s*{[\s\S]*flex-direction:\s*column/);
  assert.match(globals, /\.builder-detail-workspace\s*{[\s\S]*margin-top:\s*clamp/);
  assert.match(globals, /\.builder-detail-avatar\.fb-src-icon\s*{[\s\S]*height:\s*3\.5rem/);
  assert.match(globals, /\.builder-detail-channel-row\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto auto/);
  assert.match(globals, /@media \(max-width:\s*767px\)[\s\S]*\.builder-detail-channel-row\s*{[\s\S]*grid-template-columns:\s*1fr/);
  assert.match(source("src/components/RecentPostsList.tsx"), /className="recent-post-list"/);
  assert.doesNotMatch(globals, /\.fb-rail/);
});

test("dashboard defers heavy recommendation timeline work to a client island", () => {
  const dashboardPage = source("src/app/(workspace)/dashboard/page.tsx");
  const favoritesSection = source("src/components/FavoritePostsSection.tsx");
  const followingSection = source("src/components/FollowingRecommendationSection.tsx");
  const recommendationFeed = source("src/components/RecommendationFeed.tsx");
  const globals = source("src/app/globals.css");
  const timelineRoute = source("src/app/api/recommendations/timeline/route.ts");
  const serializer = source("src/lib/recommendation-view-model.ts");

  assert.doesNotMatch(dashboardPage, /getRecommendationTimeline/);
  assert.doesNotMatch(dashboardPage, /RecommendationFeed/);
  assert.match(dashboardPage, /FavoritePostsSection/);
  assert.match(dashboardPage, /FollowingRecommendationSection/);
  assert.match(followingSection, /"use client"/);
  assert.doesNotMatch(followingSection, /scope=\$\{scope\}/);
  assert.doesNotMatch(followingSection, /followBriefDataChanged/);
  assert.doesNotMatch(followingSection, /contentSyncStateChanged/);
  assert.doesNotMatch(followingSection, /window\.addEventListener/);
  assert.match(recommendationFeed, /Refresh/);
  assert.match(recommendationFeed, /feed-content-stack recommendation-feed/);
  assert.match(recommendationFeed, /className="recommendation-feed-actions"/);
  assert.match(recommendationFeed, /className="recommendation-snapshot-list"/);
  assert.match(recommendationFeed, /className="feed-load-more"/);
  assert.match(recommendationFeed, /className="feed-end-note"/);
  assert.match(favoritesSection, /feed-content-stack/);
  assert.match(followingSection, /feed-content-stack/);
  assert.match(favoritesSection, /className="feed-skeleton-list"/);
  assert.match(favoritesSection, /className="feed-skeleton-card"/);
  assert.match(favoritesSection, /className="feed-state-panel"/);
  assert.match(favoritesSection, /className="feed-state-inner"/);
  assert.match(favoritesSection, /className="feed-state-icon"/);
  assert.match(favoritesSection, /className="feed-state-title"/);
  assert.match(favoritesSection, /className="feed-state-desc"/);
  assert.match(followingSection, /className="feed-skeleton-list"/);
  assert.match(followingSection, /className="feed-state-panel"/);
  assert.match(followingSection, /data-tone="error"/);
  assert.match(followingSection, /className="feed-state-inner"/);
  assert.match(followingSection, /className="feed-state-icon"/);
  assert.doesNotMatch(recommendationFeed, /recommendation-feed mt-6/);
  assert.doesNotMatch(recommendationFeed, /mt-6 flex min-h-14/);
  assert.doesNotMatch(recommendationFeed, /className="item-list"|mb-5 flex flex-wrap items-center justify-between gap-3|text-sm text-\[var\(--muted\)\]/);
  assert.doesNotMatch(favoritesSection, /item-list mt-6|empty-panel mt-6/);
  assert.doesNotMatch(followingSection, /item-list mt-6|empty-panel mt-6/);
  assert.doesNotMatch(favoritesSection, /bg-black\/10|empty-panel border-dashed|flex items-start gap-3|text-lg font-semibold|mt-2 text-sm/);
  assert.doesNotMatch(followingSection, /bg-black\/10|empty-panel border-dashed|flex items-start gap-3|text-lg font-semibold|mt-2 text-sm/);
  assert.match(globals, /\.feed-content-stack\s*{[\s\S]*margin-top:\s*1\.5rem/);
  assert.match(globals, /\.recommendation-feed-actions\s*{[\s\S]*justify-content:\s*space-between/);
  assert.match(globals, /\.recommendation-snapshot-list\s*{[\s\S]*display:\s*grid/);
  assert.match(globals, /\.feed-end-note\s*{[\s\S]*font-size:\s*0\.875rem/);
  assert.match(globals, /\.feed-skeleton-card\s*{[\s\S]*min-height:\s*6rem/);
  assert.match(globals, /\.feed-state-panel\s*{[\s\S]*border:\s*1px dashed var\(--line\)/);
  assert.match(followingSection, /Loading Following recommendations/);
  assert.match(followingSection, /aria-live="polite"/);
  assert.match(timelineRoute, /export async function GET/);
  assert.match(timelineRoute, /getRecommendationTimeline/);
  assert.match(timelineRoute, /serializeRecommendationTimeline/);
  assert.match(timelineRoute, /NextResponse\.json/);
  assert.match(serializer, /serializeRecommendationTimeline/);
  assert.match(serializer, /serializeRecommendationSnapshot/);
});

test("workspace auto-refresh covers server-side data changes without manual reloads", () => {
  const workspaceLayout = source("src/app/(workspace)/layout.tsx");
  const appShell = source("src/components/AppShell.tsx");
  const workspaceAutoRefresh = source("src/components/WorkspaceAutoRefresh.tsx");
  const contentStateRoute = source("src/app/api/content-state/route.ts");
  const contentSyncState = source("src/lib/content-sync-state.ts");
  const contentSyncEvents = source("src/lib/content-sync-events.ts");
  const fetchLogPanel = source("src/components/FetchLogPanel.tsx");
  const digestLogPanel = source("src/components/DigestLogPanel.tsx");
  const digestDetails = source("src/components/DigestDetails.tsx");
  const agentTokenPanel = source("src/components/AgentTokenPanel.tsx");
  const builderLibraryList = source("src/components/BuilderLibraryList.tsx");
  const libraryHubImportForm = source("src/components/LibraryHubImportForm.tsx");

  assert.match(workspaceLayout, /contentSyncState\(session\.user\.id\)/);
  assert.match(workspaceLayout, /<WorkspaceAutoRefresh initialVersion=\{syncState\.version\} \/>/);
  assert.match(appShell, /<AppNav items=\{nav\} mode="mobile" \/>/);
  assert.match(workspaceAutoRefresh, /fetch\("\/api\/content-state"/);
  assert.match(workspaceAutoRefresh, /cache: "no-store"/);
  assert.match(workspaceAutoRefresh, /router\.refresh\(\)/);
  assert.match(workspaceAutoRefresh, /contentSyncStateChanged/);
  assert.match(workspaceAutoRefresh, /visibilitychange/);
  assert.match(workspaceAutoRefresh, /window\.addEventListener\("focus"/);
  assert.match(contentStateRoute, /Cache-Control": "no-store"/);
  assert.match(contentStateRoute, /getCurrentSession/);
  assert.match(contentStateRoute, /contentSyncState\(session\.user\.id\)/);
  assert.match(contentSyncState, /builderPoolEntry\.findMany/);
  assert.doesNotMatch(contentSyncState, /activePoolBuilderIds/);
  assert.match(contentSyncState, /digest\.aggregate/);
  assert.match(contentSyncState, /digestRun\.aggregate/);
  assert.match(contentSyncState, /libraryFetchRun\.aggregate/);
  assert.match(contentSyncState, /libraryCronJob\.findUnique/);
  assert.match(contentSyncState, /digestCronJob\.findUnique/);
  assert.doesNotMatch(contentSyncState, /feedRead\.aggregate/);
  assert.doesNotMatch(contentSyncState, /recommendationSnapshot\.aggregate/);
  assert.match(contentSyncState, /agentToken\.aggregate/);
  assert.match(contentSyncState, /userSourceTypeConfig\.aggregate/);
  assert.match(contentSyncState, /userDigestConfig\.findUnique/);
  assert.match(contentSyncState, /libraryImport\.aggregate/);
  assert.match(contentSyncState, /_sum:\s*\{ importCount: true \}/);
  assert.match(contentSyncState, /digestPipelineShare\.aggregate/);
  assert.match(contentSyncState, /digestPipelineImport\.aggregate/);
  assert.doesNotMatch(contentSyncState, /viewCount/);
  assert.doesNotMatch(contentSyncState, /libraryHubEntry\.aggregate\(\{[\s\S]*updatedAt:\s*true/);
  assert.match(contentSyncEvents, /contentSyncStateChanged/);
  assert.match(fetchLogPanel, /window\.addEventListener\(contentSyncStateChanged/);
  assert.match(digestLogPanel, /window\.addEventListener\(contentSyncStateChanged/);
  assert.match(digestLogPanel, /isRunInflight/);
  assert.match(digestDetails, /stateKey = `\$\{digestId\}/);
  assert.match(agentTokenPanel, /initialTokenSignature/);
  assert.match(builderLibraryList, /builderSubscriptionSignature/);
  assert.match(libraryHubImportForm, /importedSignature/);
});

test("skill context caps personal fetched items to keep payloads bounded", () => {
  const contextRoute = source("src/app/api/skill/context/route.ts");

  assert.match(contextRoute, /personalFetchedItemLimit/);
  assert.match(contextRoute, /take:\s*personalFetchedItemLimit/);
  assert.match(contextRoute, /personalFetchedItems/);
  assert.doesNotMatch(contextRoute, /legacyPrompts/);
  assert.doesNotMatch(contextRoute, /prompts:/);
  assert.match(contextRoute, /dryRun/);
  assert.match(contextRoute, /sourceParam/);
  // A DigestRun is recorded only for a digest prepare, never a library fetch —
  // gated by intent so library fetches don't pollute the digest history.
  assert.match(contextRoute, /const isDigest =/);
  assert.match(contextRoute, /if \(isDigest && !dryRun\)/);
});

test("dashboard subscription feed owns the paginated digest archive", () => {
  const dashboardPage = source("src/app/(workspace)/dashboard/page.tsx");
  const historyPage = source("src/app/history/page.tsx");
  const digestDetails = source("src/components/DigestDetails.tsx");
  const digestRoute = source("src/app/api/digests/[digestId]/route.ts");
  const digestPipelineVisibilityToggle = source("src/components/DigestPipelineVisibilityToggle.tsx");

  assert.match(dashboardPage, /digestPickerSize/);
  assert.match(dashboardPage, /digest\?: string \| string\[\]/);
  assert.match(dashboardPage, /pipeline\?: string \| string\[\]/);
  assert.match(dashboardPage, /selectedPipeline/);
  assert.match(dashboardPage, /digestPipelineImport\.findMany/);
  assert.match(dashboardPage, /take:\s*digestPickerSize/);
  assert.match(dashboardPage, /digestSummarySelect/);
  assert.match(dashboardPage, /id:\s*true/);
  assert.match(dashboardPage, /headlineSummary:\s*true/);
  assert.match(dashboardPage, /select:\s*digestSummarySelect/);
  assert.doesNotMatch(dashboardPage, /digest\.content/);
  assert.match(dashboardPage, /DigestDetails/);
  assert.match(dashboardPage, /headerAction=/);
  assert.match(digestDetails, /headlineSummary/);
  assert.match(digestDetails, /digest-headline-summary/);
  assert.match(digestDetails, /digest-headline-action/);
  assert.match(digestDetails, /item-headline-preview/);
  assert.match(digestDetails, /digestPreviewFromContent/);
  assert.match(digestDetails, /isLatest/);
  assert.match(digestDetails, /showContents=\{false\}/);
  assert.match(source("src/app/globals.css"), /digest-picker/);
  assert.match(source("src/app/globals.css"), /digest-latest-mark/);
  assert.match(source("src/app/globals.css"), /digest-section-summary-static/);
  assert.match(source("src/app/globals.css"), /item-headline-preview/);
  assert.match(digestRoute, /headlineSummary/);
  assert.match(dashboardPage, /DigestPipelineSelector/);
  assert.match(dashboardPage, /DigestArchiveSelector/);
  assert.match(dashboardPage, /formatDigestPickerDate/);
  assert.match(dashboardPage, /CountMeta/);
  assert.match(dashboardPage, /AI Digest/);
  assert.match(dashboardPage, /DigestPipelineVisibilityToggle/);
  assert.match(dashboardPage, /ownPipelineShared/);
  assert.match(dashboardPage, /digestPipelineShare\.findUnique/);
  assert.match(dashboardPage, /digestCronJob\.findUnique/);
  assert.match(dashboardPage, /getDigestRuns\(userId, 25, "cron"\)/);
  assert.match(digestPipelineVisibilityToggle, /Share to Hub/);
  assert.match(digestPipelineVisibilityToggle, /fetch\("\/api\/digest-pipelines\/share"/);
  assert.match(digestPipelineVisibilityToggle, /method: nextShared \? "POST" : "DELETE"/);
  assert.match(digestPipelineVisibilityToggle, /aria-pressed=\{shared\}/);
  assert.match(dashboardPage, /Imported digest view/);
  assert.match(dashboardPage, /isOwnPipeline \? \(/);
  assert.match(dashboardPage, /isOwnPipeline[\s\S]*<SkillPromptActions/);
  assert.match(dashboardPage, /isOwnPipeline[\s\S]*<DigestLogPanel/);
  assert.match(dashboardPage, /initialCronJob=\{digestCronJob\}/);
  assert.match(dashboardPage, /initialCronRuns=\{digestCronRuns\}/);
  assert.match(dashboardPage, /showStop=\{showStopDigestCron\}/);
  assert.match(dashboardPage, /digestHref/);
  assert.match(dashboardPage, /aria-label="Digest archive"/);
  assert.match(historyPage, /redirect\("\/dashboard\?tab=ai-digest"\)/);
  assert.doesNotMatch(historyPage, /AppShell/);
  assert.match(digestDetails, /"use client"/);
  assert.match(digestDetails, /fetch\(`\/api\/digests\/\$\{digestId\}`/);
  assert.match(digestDetails, /digest-latest-mark/);
  assert.match(digestDetails, /Loading digest/);
  assert.match(digestDetails, /aria-live="polite"/);
  assert.match(digestRoute, /export async function GET/);
  assert.match(digestRoute, /content: true/);
  assert.match(digestRoute, /digestPipelineImport\.findFirst/);
  assert.match(digestRoute, /ownerUserId: digest\.userId/);
  assert.match(digestRoute, /isPublic:\s*true/);
  assert.match(digestRoute, /NextResponse\.json/);
});

test("search page uses a client form with pending feedback", () => {
  const searchPage = source("src/app/(workspace)/search/page.tsx");
  const searchForm = source("src/components/SearchForm.tsx");
  const globals = source("src/app/globals.css");

  assert.match(searchPage, /@\/components\/SearchForm/);
  assert.match(searchPage, /searchPageSize/);
  assert.match(searchPage, /relatedSearchSuggestions/);
  assert.match(searchPage, /didYouMeanSearch/);
  assert.match(searchPage, /shouldUseCorrectedSearch/);
  assert.match(searchPage, /<Suspense/);
  assert.match(searchPage, /SearchResultsFallback/);
  assert.match(searchPage, /SearchResultsSection/);
  assert.match(globals, /\.search-result-skeleton/);
  assert.match(searchPage, /className="fb-page-head search-hero"/);
  assert.match(searchPage, /className="fb-title"/);
  assert.match(searchPage, /className="search-hero-form"/);
  assert.doesNotMatch(searchPage, /fb-m-search/);
  assert.doesNotMatch(searchPage, /search-page-active/);
  assert.doesNotMatch(searchPage, /serif text-\[1\.875rem\]/);
  assert.match(globals, /\.search-results-shell\s*{[\s\S]*max-width:\s*var\(--workspace-max\)/);
  assert.match(globals, /\.search-hero\s*{[\s\S]*grid-template-columns:/);
  assert.match(globals, /\.search-hero-form \.search-form\s*{[\s\S]*margin-top:\s*0/);
  assert.match(searchPage, /Search instead for/);
  assert.match(searchPage, /isShowingCorrectedResults/);
  assert.match(searchPage, /Advanced search/);
  assert.match(searchPage, /"model \* pricing"/);
  assert.match(searchPage, /-"pricing page"/);
  assert.match(searchPage, /\+open/);
  assert.match(searchPage, /models OR benchmarks/);
  assert.match(searchPage, /"model pricing" OR "launch notes"/);
  assert.match(searchPage, /\("model pricing" OR "launch notes"\) open/);
  assert.match(searchPage, /model AROUND\(3\) pricing/);
  assert.match(searchPage, /site:example\.com/);
  assert.match(searchPage, /site:example\.com\/articles/);
  assert.match(searchPage, /-site:example\.com/);
  assert.match(searchPage, /intitle:launch/);
  assert.match(searchPage, /-intitle:enterprise/);
  assert.match(searchPage, /allintitle:model pricing/);
  assert.match(searchPage, /-allintitle:enterprise launch/);
  assert.match(searchPage, /intext:transcript/);
  assert.match(searchPage, /allintext:model pricing/);
  assert.match(searchPage, /inurl:release/);
  assert.match(searchPage, /allinurl:release model/);
  assert.match(searchPage, /type:feed/);
  assert.match(searchPage, /filetype:digest/);
  assert.match(searchPage, /-filetype:digest/);
  assert.match(searchPage, /after:2026-01-01/);
  assert.match(searchPage, /-enterprise/);
  assert.match(searchPage, /ActiveSearchFilters/);
  assert.match(searchPage, /searchHighlightTerms/);
  assert.match(searchPage, /search-result-refinements/);
  assert.match(searchPage, /className="search-result-source-copy"/);
  assert.match(searchPage, /className="search-result-refinement-list"/);
  assert.match(searchPage, /More from this source/);
  assert.match(searchPage, /Search tools/);
  assert.match(searchPage, /Clear all/);
  assert.match(searchPage, /className="search-filter-chip-row"/);
  assert.match(searchPage, /className="search-filter-chip"/);
  assert.match(searchPage, /className="search-filter-label"/);
  assert.match(searchPage, /className="search-filter-clear"/);
  assert.doesNotMatch(searchPage, /className="flex flex-wrap items-center gap-2"/);
  assert.doesNotMatch(searchPage, /className="fb-filter-chip"/);
  assert.doesNotMatch(searchPage, /className="ml-1 text-xs font-bold text-\[var\(--accent\)\]"/);
  assert.doesNotMatch(searchPage, /className="mt-2 flex flex-wrap gap-2"/);
  assert.match(globals, /\.search-result-source-copy\s*{[\s\S]*min-width:\s*0/);
  assert.match(globals, /\.search-result-refinement-list\s*{[\s\S]*display:\s*flex/);
  assert.match(searchPage, /SearchQueryInsights/);
  assert.match(searchPage, /SearchTypeTabs/);
  assert.match(searchPage, /counts=\{hasQuery \? typeCounts : null\}/);
  assert.match(searchPage, /buildQueryInsightItems/);
  assert.match(searchPage, /search-insights/);
  assert.match(searchPage, /search-insight-card/);
  assert.match(searchPage, /Query understood/);
  assert.match(searchPage, /Use best match/);
  assert.match(searchPage, /Search all result types/);
  assert.match(searchPage, /Search all time/);
  assert.match(searchPage, /search-empty-actions/);
  assert.match(searchPage, /stripSearchQueryOperators/);
  assert.match(searchPage, /clearAllSearchHref/);
  assert.match(searchPage, /Remove title search terms/);
  assert.match(searchPage, /Remove text search terms/);
  assert.match(searchPage, /Remove URL search terms/);
  assert.match(searchPage, /Remove required terms/);
  assert.match(searchPage, /Must include/);
  assert.match(searchPage, /Remove excluded title terms/);
  assert.match(searchPage, /Remove excluded sites/);
  assert.match(searchPage, /Remove excluded phrases/);
  assert.match(searchPage, /Remove excluded file types/);
  assert.match(searchPage, /Remove file type/);
  assert.match(searchPage, /normalizeSearchTime/);
  assert.match(searchForm, /useTransition/);
  assert.match(searchForm, /Searching/);
  assert.match(searchForm, /localStorage\.getItem\("builder-blog-searches"\)/);
  assert.match(searchForm, /normalizeRecentSearches/);
  assert.match(searchForm, /Match style/);
  assert.match(searchForm, /variant\?: "page" \| "header"/);
  assert.match(searchForm, /header-search-suggestion/);
  assert.match(searchForm, /\/api\/search\/suggest/);
  assert.match(searchForm, /Time range/);
  assert.match(searchForm, /Sort by/);
  assert.match(searchForm, /Custom date range/);
  assert.match(searchForm, /withDateSearchOperators/);
  assert.match(searchForm, /name="after"/);
  assert.match(searchForm, /name="before"/);
  assert.match(searchForm, /useRef<HTMLInputElement>/);
  assert.match(searchForm, /Clear search query/);
  assert.match(searchForm, /clearQuery/);
  assert.match(searchForm, /inputRef\.current\?\.focus/);
  assert.match(searchForm, /recentSuggestionKeys/);
  assert.match(searchForm, /Remove recent search/);
  assert.match(searchForm, /removeRecentSearch/);
  assert.match(searchForm, /normalizeSuggestionKey/);
  assert.doesNotMatch(searchForm, /datalist/);
  assert.match(searchForm, /\/api\/search\/suggest/);
  assert.match(searchForm, /AbortController/);
  assert.match(searchForm, /aria-live="polite"/);
  assert.match(searchForm, /search-suggestion-dropdown/);
  assert.match(searchForm, /search-suggestion-title/);
  assert.match(searchForm, /search-suggestion-detail/);
  assert.match(searchForm, /normalizeAutocompleteItems/);
  assert.match(searchForm, /onKeyDown/);
  assert.match(searchForm, /ArrowDown/);
  assert.match(searchForm, /ArrowUp/);
  assert.match(searchForm, /Escape/);
  assert.match(searchForm, /aria-activedescendant/);
  assert.match(searchForm, /autoComplete="off"/);
  assert.match(searchForm, /autoCorrect="off"/);
  assert.match(searchForm, /spellCheck=\{false\}/);
  assert.match(searchForm, /role="listbox"/);
  assert.match(searchForm, /role="option"/);
  assert.match(searchForm, /submitSuggestion\(activeSuggestion, event\.currentTarget\.form\)/);
  assert.match(searchForm, /className="search-suggestion-chip"[\s\S]*submitSuggestion\(suggestion, inputRef\.current\?\.form \?\? null\)[\s\S]*type="button"/);
  assert.doesNotMatch(searchForm, /name="suggestion"/);
  assert.doesNotMatch(searchForm, /Lucky/);
  assert.doesNotMatch(searchForm, /lucky/);
  assert.doesNotMatch(searchForm, /type="radio"/);
  assert.match(globals, /\.search-suggestion-dropdown/);
  assert.doesNotMatch(globals, /search-page-active/);
  assert.doesNotMatch(globals, /search-heading/);
  assert.doesNotMatch(globals, /\.fb-m-search/);
});

test("search suggestions API exists for autocomplete-style queries", () => {
  const suggestRoute = source("src/app/api/search/suggest/route.ts");

  assert.match(suggestRoute, /relatedSearchSuggestions/);
  assert.match(suggestRoute, /searchUserLibrary/);
  assert.match(suggestRoute, /items:/);
  assert.match(suggestRoute, /titlePrefixCompletions/);
  assert.match(suggestRoute, /claude code/);
  assert.match(suggestRoute, /NextResponse/);
});

test("user library search can fetch operator-only candidate sets", () => {
  const userSearch = source("src/lib/user-search.ts");
  const searchPage = source("src/app/(workspace)/search/page.tsx");
  const searchLib = source("src/lib/search.ts");

  assert.match(userSearch, /terms\.length > 0/);
  assert.match(userSearch, /builderSearchConditions\(terms\)/);
  assert.match(userSearch, /feedSearchConditions\(terms\)/);
  assert.match(userSearch, /digestSearchConditions\(terms\)/);
  assert.match(userSearch, /entityId: true/);
  assert.match(userSearch, /externalUrl: builder\.sourceUrl \?\? builder\.fetchUrl/);
  assert.match(userSearch, /url: builder\.entityId \? `\/builder\/\$\{builder\.entityId\}` : `\/builders#\$\{builder\.id\}`/);
  assert.match(searchLib, /externalUrl\?: string \| null/);
  assert.match(searchLib, /documentSiteMatches\(document, parsedQuery\.site\)/);
  assert.match(searchPage, /const originalUrl = result\.externalUrl \?\? \(titleIsExternal \? result\.url : null\)/);
  assert.match(searchPage, /className="post-read-original"/);
  assert.match(searchPage, /View original/);
  assert.doesNotMatch(searchPage, /className="search-result-open"/);
});

test("primary tabs use local loading fallbacks instead of full-route loaders", () => {
  assert.equal(existsSync(join(root, "src/app/history/loading.tsx")), true);
  for (const path of [
    "src/app/(workspace)/builders/loading.tsx",
    "src/app/(workspace)/library-hub/loading.tsx",
    "src/app/(workspace)/search/loading.tsx",
  ]) {
    assert.equal(existsSync(join(root, path)), false, path);
  }
  const buildersPage = source("src/app/(workspace)/builders/page.tsx");
  const libraryHubPage = source("src/app/(workspace)/library-hub/page.tsx");
  const searchPage = source("src/app/(workspace)/search/page.tsx");
  assert.match(buildersPage, /<Suspense fallback=\{<BuilderStatsFallback \/>/);
  assert.match(buildersPage, /<Suspense fallback=\{<BuilderSectionsFallback \/>/);
  assert.match(buildersPage, /function BuilderSectionsFallback/);
  assert.match(buildersPage, /className="workspace-content-stack"/);
  assert.doesNotMatch(buildersPage, /sources-sync-section mt-5/);
  assert.doesNotMatch(buildersPage, /mt-6 grid gap-5/);
  assert.match(libraryHubPage, /<Suspense fallback=\{<LibraryHubImportFallback \/>/);
  assert.match(libraryHubPage, /function LibraryHubImportFallback/);
  assert.match(libraryHubPage, /className="workspace-content-stack"/);
  assert.match(libraryHubPage, /className="library-hub-page-count"/);
  assert.match(libraryHubPage, /className="library-hub-skeleton-line is-wide"/);
  assert.match(libraryHubPage, /className="library-hub-skeleton-copy"/);
  assert.match(libraryHubPage, /className="library-hub-skeleton-line is-kicker"/);
  assert.match(libraryHubPage, /className="library-hub-skeleton-line is-title"/);
  assert.match(libraryHubPage, /className="library-hub-skeleton-line is-body"/);
  assert.match(libraryHubPage, /className="library-hub-skeleton-pill"/);
  assert.match(libraryHubPage, /className="library-hub-card library-hub-skeleton-card"/);
  assert.doesNotMatch(libraryHubPage, /className="mt-6"/);
  assert.doesNotMatch(libraryHubPage, /className="mt-10"/);
  assert.doesNotMatch(libraryHubPage, /bg-black\/10/);
  assert.doesNotMatch(libraryHubPage, /className="flex items-center gap-2"/);
  assert.doesNotMatch(libraryHubPage, /className="min-w-0 flex-1"/);
  assert.match(libraryHubPage, /className="hub-list-stack fb-hub-list"/);
  assert.doesNotMatch(libraryHubPage, /className="fb-hub-list mt-5"/);
  assert.match(source("src/components/LibraryHubImportForm.tsx"), /className="hub-import-section"/);
  assert.match(source("src/components/LibraryHubImportForm.tsx"), /className="hub-form-error"/);
  assert.match(source("src/components/LibraryHubImportForm.tsx"), /"hub-list-region has-filters"/);
  assert.match(source("src/components/LibraryHubImportForm.tsx"), /className="fb-hub-card-head"/);
  assert.match(source("src/components/LibraryHubImportForm.tsx"), /className="fb-hub-sources-summary"/);
  assert.match(source("src/components/LibraryHubImportForm.tsx"), /className="fb-hub-card-stats"/);
  assert.doesNotMatch(source("src/components/LibraryHubImportForm.tsx"), /AVATAR_COLORS/);
  assert.doesNotMatch(source("src/components/LibraryHubImportForm.tsx"), /style=\{\{/);
  assert.match(source("src/components/DigestPipelineImportForm.tsx"), /className="hub-section-copy"/);
  assert.match(source("src/components/DigestPipelineImportForm.tsx"), /className="hub-list-stack fb-hub-list"/);
  assert.match(source("src/components/DigestPipelineImportForm.tsx"), /className="fb-hub-card-head"/);
  assert.match(source("src/components/DigestPipelineImportForm.tsx"), /className="fb-hub-digest-preview"/);
  assert.match(source("src/components/DigestPipelineImportForm.tsx"), /className="fb-hub-card-stats"/);
  assert.doesNotMatch(source("src/components/DigestPipelineImportForm.tsx"), /<section className="mt-10"/);
  assert.doesNotMatch(source("src/components/DigestPipelineImportForm.tsx"), /className="fb-hub-list mt-5"/);
  assert.match(source("src/app/globals.css"), /\.hub-list-region\.has-filters/);
  assert.match(source("src/app/globals.css"), /\.hub-section-copy/);
  assert.match(source("src/app/globals.css"), /\.library-hub-page-count\s*{[\s\S]*display:\s*flex/);
  assert.match(source("src/app/globals.css"), /\.library-hub-skeleton-line,[\s\S]*\.library-hub-skeleton-card\s*{[\s\S]*color-mix\(in oklch, var\(--ink\) 10%, transparent\)/);
  assert.match(source("src/app/globals.css"), /\.library-hub-skeleton-card\s*{[\s\S]*min-height:\s*11rem/);
  assert.match(source("src/app/globals.css"), /\.fb-hub-card-head\s*{/);
  assert.match(source("src/app/globals.css"), /\.fb-hub-source-row\s*{[\s\S]*grid-template-columns:\s*3\.5rem minmax\(0,\s*1fr\) minmax\(0,\s*auto\)/);
  assert.match(source("src/app/globals.css"), /\.fb-hub-source-avatar\[data-avatar-tone="0"\]\s*{[\s\S]*oklch/);
  assert.match(source("src/app/globals.css"), /\.fb-hub-digest-preview\s*{/);
  assert.match(searchPage, /<Suspense[\s\S]*fallback=\{[\s\S]*<SearchResultsFallback/);
});

test("builders page avoids a global fetched-content query", () => {
  const buildersPage = source("src/app/(workspace)/builders/page.tsx");
  const builderLibraryList = source("src/components/BuilderLibraryList.tsx");

  assert.doesNotMatch(buildersPage, /RecentFetchedContent/);
  assert.doesNotMatch(buildersPage, /prisma\.feedItem\.findMany/);
  assert.match(builderLibraryList, /BuilderFeedItems/);
});

test("builders page exposes per-builder fetched posts ordered by time", () => {
  const buildersPage = source("src/app/(workspace)/builders/page.tsx");
  const addBuilderForm = source("src/components/AddBuilderForm.tsx");
  const builderLibraryList = source("src/components/BuilderLibraryList.tsx");
  const builderFeedItems = source("src/components/BuilderFeedItems.tsx");
  const recommendationItemPage = source("src/app/(workspace)/recommendations/items/[feedItemId]/page.tsx");
  const postCard = source("src/components/PostCard.tsx");
  const globals = source("src/app/globals.css");
  const personalBuilderRoute = source("src/app/api/builders/personal/route.ts");
  const feedItemsRoute = source("src/app/api/builders/[builderId]/feed-items/route.ts");

  assert.doesNotMatch(buildersPage, /feedItems:\s*{/);
  assert.match(buildersPage, /title=\{data\.isAdmin \? adminCommunityLibraryName : "Private library"\}[\s\S]*defaultOpen/);
  assert.doesNotMatch(builderLibraryList, /function BuilderStats/);
  assert.match(builderLibraryList, /latestPostCreatedAt=\{builder\.latestPostCreatedAt\}/);
  assert.doesNotMatch(builderLibraryList, /CountMeta/);
  assert.doesNotMatch(builderLibraryList, /\{builder\.feedItemCount\}\s*items/);
  assert.doesNotMatch(builderLibraryList, /No posts yet/);
  assert.doesNotMatch(builderLibraryList, /builder-library-stats/);
  assert.match(builderLibraryList, /className="builder-library-error"/);
  assert.doesNotMatch(builderLibraryList, /mt-2 text-sm text-\[var\(--danger\)\]/);
  assert.doesNotMatch(builderLibraryList, /builder-posts-latest/);
  assert.doesNotMatch(builderLibraryList, /latest \{formatCompactDate/);
  assert.doesNotMatch(builderLibraryList, /feedItemCount\}\s*items/);
  assert.match(buildersPage, /className="source-sync-skeleton-line"/);
  assert.match(buildersPage, /className="source-sync-skeleton-panel"/);
  assert.match(buildersPage, /className="source-stat-skeleton"/);
  assert.match(buildersPage, /className="source-section-skeleton-title"/);
  assert.match(buildersPage, /className="source-section-skeleton-desc"/);
  assert.match(buildersPage, /className="source-section-skeleton-chip source-section-skeleton-chip--short"/);
  assert.match(buildersPage, /className="source-section-skeleton-row"/);
  assert.match(buildersPage, /className="source-section-skeleton-card"/);
  assert.doesNotMatch(buildersPage, /bg-black\/10|className="h-/);
  assert.match(
    builderFeedItems,
    /<span>Posts<\/span>[\s\S]*label=\{items \? "loaded" : "summarized"\}[\s\S]*className="builder-posts-latest"[\s\S]*latest \{formatCompactDate/,
  );
  assert.match(builderFeedItems, /latest \{formatCompactDate\(new Date\(latestPostCreatedAt\)\)\}/);
  assert.match(builderFeedItems, /className="builder-post-loading-line"/);
  assert.match(builderFeedItems, /className="builder-post-loading-card"/);
  assert.match(builderFeedItems, /className="builder-post-state builder-post-state--error"/);
  assert.match(builderFeedItems, /className="builder-post-state"/);
  assert.doesNotMatch(builderFeedItems, /bg-black\/10|className="h-/);
  assert.doesNotMatch(builderFeedItems, /className="p-4 text-sm/);
  assert.match(builderFeedItems, /timeZone:\s*"UTC"/);
  assert.match(buildersPage, /publishedAt:\s*{\s*not:\s*null\s*}/);
  assert.match(buildersPage, /Imported libraries/);
  assert.match(buildersPage, /importedLibrarySections/);
  assert.match(buildersPage, /library-section-panel-indented/);
  assert.doesNotMatch(buildersPage, /Central defaults|Central library/);
  assert.match(buildersPage, /BuilderLibraryList/);
  assert.match(builderLibraryList, /BuilderFeedItems/);
  // AddBuilderForm is now embedded inside PrivateLibraryPanel rather
  // than imported directly into the builders page. Keep both ends of the
  // composition asserted so renames break this test rather than silently
  // hiding the add-source form.
  assert.match(buildersPage, /PrivateLibraryPanel/);
  assert.match(source("src/components/PrivateLibraryPanel.tsx"), /AddBuilderForm/);
  assert.doesNotMatch(buildersPage, /addPersonalBuilderAction/);
  assert.match(addBuilderForm, /"use client"/);
  assert.match(addBuilderForm, /fetch\("\/api\/builders\/personal"/);
  assert.match(addBuilderForm, /builderLibraryBuilderAdded/);
  // Source type is now a segmented icon+label picker (role="radiogroup"),
  // not a native <select name="sourceType">. The form submits sourceType
  // via React state in the fetch body, not via form-data.
  assert.match(addBuilderForm, /role="radiogroup"/);
  assert.match(addBuilderForm, /aria-label="Source type"/);
  assert.match(addBuilderForm, /name="sourceValue"/);
  assert.match(addBuilderForm, /Handle or URL/);
  assert.match(addBuilderForm, /className="add-source-form"/);
  assert.match(addBuilderForm, /className="add-source-type-list"/);
  assert.match(addBuilderForm, /className="add-source-primary-row"/);
  assert.match(addBuilderForm, /className="add-source-name-row"/);
  assert.match(addBuilderForm, /className="add-source-callout"/);
  assert.match(addBuilderForm, /add-source-text-action/);
  assert.doesNotMatch(addBuilderForm, /style=\{\{/);
  assert.doesNotMatch(addBuilderForm, /className="mt-1 rounded-md border/);
  assert.match(source("src/components/PrivateLibraryPanel.tsx"), /className="add-source-panel fb-panel"/);
  assert.doesNotMatch(source("src/components/PrivateLibraryPanel.tsx"), /className="fb-panel mb-3"/);
  assert.match(globals, /\.add-source-form/);
  assert.match(globals, /\.add-source-callout/);
  assert.match(globals, /\.source-sync-skeleton-line,[\s\S]*\.source-section-skeleton-card\s*{[\s\S]*color-mix\(in oklch, var\(--ink\) 10%, transparent\)/);
  assert.match(globals, /\.source-stat-skeleton\s*{[\s\S]*border-radius:\s*999px/);
  assert.match(globals, /\.builder-library-error\s*{[\s\S]*color:\s*var\(--danger\)/);
  assert.match(globals, /\.builder-post-loading-card\s*{[\s\S]*height:\s*4rem/);
  assert.match(globals, /\.builder-post-state\s*{[\s\S]*padding:\s*1rem/);
  assert.match(globals, /\.builder-post-state--error\s*{[\s\S]*color:\s*var\(--danger\)/);
  assert.doesNotMatch(globals, /\.item-list\s*{/);
  assert.doesNotMatch(globals, /\.add-builder-form/);
  assert.doesNotMatch(globals, /\.add-builder-grid/);
  assert.match(personalBuilderRoute, /export async function POST/);
  assert.match(personalBuilderRoute, /resolvePersonalBuilderInput/);
  assert.match(personalBuilderRoute, /NextResponse\.json/);
  assert.doesNotMatch(personalBuilderRoute, /redirect\(/);
  assert.match(builderLibraryList, /SourceBadge/);
  assert.doesNotMatch(buildersPage, /Technical details/);
  assert.doesNotMatch(buildersPage, /name="handle"/);
  assert.doesNotMatch(buildersPage, /name="sourceUrl"/);
  assert.doesNotMatch(buildersPage, /name="fetchUrl"/);
  assert.match(builderFeedItems, /"use client"/);
  assert.match(builderFeedItems, /fetch\(`\/api\/builders\/\$\{builderId\}\/feed-items`/);
  // UI copy avoids "Fetched" in the row; detailed content still renders
  // through PostCard.
  assert.match(builderFeedItems, /<span>Posts<\/span>/);
  assert.match(builderFeedItems, /PostCard/);
  assert.match(postCard, /Summary/);
  assert.match(postCard, /export function PostCard/);
  assert.match(postCard, /post-detail-card/);
  assert.match(postCard, /post-detail-title/);
  assert.match(postCard, /post-detail-body/);
  assert.match(postCard, /className="fetched-post-summary-text"/);
  assert.match(postCard, /className="fetched-post-raw"/);
  assert.match(postCard, /See more/);
  assert.match(postCard, /Raw content/);
  assert.match(postCard, /View original/);
  assert.doesNotMatch(postCard, /whitespace-pre-wrap text-sm leading-6|mt-3 whitespace-pre-wrap rounded-lg/);
  assert.match(globals, /\.fetched-post-summary-text\s*{[\s\S]*white-space:\s*pre-wrap/);
  assert.match(globals, /\.fetched-post-raw\s*{[\s\S]*border:\s*1px solid var\(--line\)/);
  assert.match(globals, /\.digest-rich \.fetched-post-summary-text\s*{[\s\S]*line-height:\s*1\.72/);
  assert.match(postCard, /\/builder\/\$\{builder\.entityId\}/);
  assert.match(recommendationItemPage, /page-pad reading-page/);
  assert.match(recommendationItemPage, /className="reading-page-nav"/);
  assert.match(recommendationItemPage, /className="button-light button-compact reading-back-link"/);
  assert.match(recommendationItemPage, /showDebugActions=\{false\}/);
  assert.equal((recommendationItemPage.match(/Back to feed/g) ?? []).length, 1);
  assert.doesNotMatch(recommendationItemPage, /extraActions=/);
  assert.match(globals, /\.reading-page\s*{[\s\S]*width:\s*min\(100%,\s*58rem\)/);
  assert.match(globals, /\.reading-page-nav\s*{[\s\S]*margin-bottom:\s*1\.35rem/);
  assert.match(globals, /\.post-detail-card\.feed-card/);
  assert.match(globals, /\.post-detail-card \.post-footer\s*{[\s\S]*border-top:/);
  assert.match(feedItemsRoute, /fetchDedupedFeedForEntities/);
  assert.match(feedItemsRoute, /activePoolBuilderIds/);
  assert.match(feedItemsRoute, /NextResponse\.json/);
});

test("digest posts use source detail headings and unified original links", () => {
  const digestContent = source("src/components/DigestContent.tsx");
  const dashboardPage = source("src/app/(workspace)/dashboard/page.tsx");
  const globals = source("src/app/globals.css");

  assert.match(digestContent, /DigestSourceLink/);
  assert.match(digestContent, /digest-group-source-link/);
  assert.match(digestContent, /sourceLinkForSource/);
  assert.match(digestContent, /PostCard/);
  assert.match(digestContent, /showDebugActions=\{false\}/);
  assert.match(digestContent, /digest-source-summary/);
  assert.doesNotMatch(digestContent, /Watch on YouTube/);
  assert.match(dashboardPage, /digestSourceLinksForUser/);
  assert.match(dashboardPage, /sourceLinks=\{sourceLinks\}/);
  assert.match(globals, /\.digest-group-heading/);
  assert.match(globals, /\.digest-group-source-link/);
});

test("library hub exposes share and multi-import flows", () => {
  const appShell = source("src/components/AppShell.tsx");
  const workspaceLayout = source("src/app/(workspace)/layout.tsx");
  const buildersPage = source("src/app/(workspace)/builders/page.tsx");
  const builderActions = source("src/components/BuilderLibraryActions.tsx");
  const visibilityToggle = source("src/components/LibraryVisibilityToggle.tsx");
  const builderLibraryList = source("src/components/BuilderLibraryList.tsx");
  const builderLibraryStats = source("src/components/BuilderLibraryStats.tsx");
  const builderLibraryEvents = source("src/lib/builder-library-events.ts");
  const builderLibraryState = source("src/lib/builder-library-state.ts");
  const libraryImportRemoveButton = source("src/components/LibraryImportRemoveButton.tsx");
  const builderPool = source("src/lib/builder-pool.ts");
  const visibilityRoute = source("src/app/api/library-hub/personal-availability/route.ts");
  const builderSubscriptionRoute = source("src/app/api/builders/[builderId]/subscription/route.ts");
  const builderLibraryRoute = source("src/app/api/builders/[builderId]/library/route.ts");
  const builderSubscribeAllRoute = source("src/app/api/builders/subscriptions/route.ts");
  const hubImportForm = source("src/components/LibraryHubImportForm.tsx");
  const hubImportRoute = source("src/app/api/library-hub/imports/route.ts");
  const digestPipelineForm = optionalSource("src/components/DigestPipelineImportForm.tsx");
  const digestPipelineVisibilityToggle = source("src/components/DigestPipelineVisibilityToggle.tsx");
  const digestPipelineTitleEditor = optionalSource("src/components/DigestPipelineTitleEditor.tsx");
  const digestPipelineShareRoute = optionalSource("src/app/api/digest-pipelines/share/route.ts");
  const digestPipelineImportRoute = optionalSource("src/app/api/digest-pipelines/imports/route.ts");
  const digestPipelineRemoveRoute = optionalSource("src/app/api/digest-pipelines/imports/[pipelineId]/route.ts");
  const hubPage = source("src/app/(workspace)/library-hub/page.tsx");
  const globals = source("src/app/globals.css");
  const dashboardPage = source("src/app/(workspace)/dashboard/page.tsx");
  const skillRoute = source("src/app/api/skill/builders/route.ts");
  const schema = source("prisma/schema.prisma");

  assert.match(appShell, /library-hub/);
  assert.doesNotMatch(appShell, /UserDataAutoRefresh/);
  assert.doesNotMatch(workspaceLayout, /builderLibraryState/);
  assert.match(workspaceLayout, /WorkspaceAutoRefresh/);
  assert.doesNotMatch(appShell, /\{ href: "\/admin"/);
  assert.match(appShell, /UserMenu/);
  assert.match(buildersPage, /LibraryVisibilityToggle/);
  assert.match(buildersPage, /adminCommunityLibraryName/);
  assert.match(buildersPage, /ensureAdminCommunityLibrary/);
  assert.doesNotMatch(buildersPage, /adminCommunityBuilders/);
  assert.doesNotMatch(buildersPage, /ownSharedLibrary\?\.items\.map/);
  assert.match(buildersPage, /ownSharedLibrary\._count\.items !== privateBuilders\.length/);
  assert.match(buildersPage, /BuilderLibraryList/);
  assert.match(buildersPage, /BuilderLibraryStats/);
  assert.doesNotMatch(buildersPage, /BuilderLibraryAutoRefresh/);
  assert.doesNotMatch(buildersPage, /builderLibraryState/);
  assert.equal(existsSync(join(root, "src/components/BuilderLibraryAutoRefresh.tsx")), false);
  assert.equal(existsSync(join(root, "src/app/api/builders/library-state/route.ts")), false);
  assert.match(builderLibraryList, /BuilderLibraryActions/);
  assert.doesNotMatch(buildersPage, /togglePersonalLibraryHubAvailabilityAction/);
  assert.doesNotMatch(buildersPage, /subscribeAllLibraryBuildersAction/);
  assert.doesNotMatch(buildersPage, /unsubscribeBuilderAction/);
  assert.doesNotMatch(buildersPage, /removeBuilderFromLibraryAction/);
  assert.match(visibilityToggle, /"use client"/);
  assert.match(visibilityToggle, /fetch\("\/api\/library-hub\/personal-availability"/);
  assert.match(visibilityToggle, /library-visibility-toggle/);
  assert.match(visibilityToggle, /aria-pressed/);
  assert.match(visibilityRoute, /export async function PATCH/);
  assert.match(visibilityRoute, /unsharePersonalLibraryFromHub/);
  assert.match(visibilityRoute, /adminCommunityLibraryName/);
  assert.doesNotMatch(visibilityRoute, /redirect\(/);
  assert.match(builderActions, /"use client"/);
  assert.match(builderActions, /allowRemove = true/);
  assert.match(builderActions, /allowRemove \? \(/);
  assert.match(builderActions, /fetch\(`\/api\/builders\/\$\{builderId\}\/subscription`/);
  assert.match(builderActions, /fetch\(`\/api\/builders\/\$\{builderId\}\/library`/);
  assert.match(builderActions, /onRemoveStateChange\?\.\(builderId, true\)/);
  assert.match(builderActions, /onRemoveStateChange\?\.\(builderId, false\)/);
  assert.match(builderActions, /onSubscriptionStateChange\?\.\(builderId, nextSubscribed, previousSubscribed\)/);
  assert.match(builderActions, /fetch\("\/api\/builders\/subscriptions"/);
  assert.match(builderLibraryList, /"use client"/);
  assert.match(builderLibraryList, /removedBuilderIds/);
  assert.match(builderLibraryList, /subscribedByBuilderId/);
  assert.match(builderLibraryList, /setRemovedBuilderIds/);
  assert.match(builderLibraryList, /dispatchEvent/);
  assert.match(builderLibraryList, /builderLibraryBuilderAdded/);
  assert.match(builderLibraryList, /allBuilders\s*\.\s*filter/);
  assert.match(builderLibraryList, /onRemoveStateChange/);
  assert.match(builderLibraryList, /onSubscriptionStateChange/);
  assert.match(builderLibraryList, /BuilderFeedItems/);
  assert.match(builderLibraryStats, /"use client"/);
  assert.match(builderLibraryStats, /builderLibraryStatsChanged/);
  assert.match(builderLibraryStats, /addEventListener/);
  assert.match(builderLibraryStats, /SubscribeAllLibraryBuildersButton/);
  assert.match(builderLibraryState, /builder\.aggregate/);
  assert.match(builderLibraryState, /feedItem\.aggregate/);
  assert.doesNotMatch(builderLibraryState, /digest\.aggregate/);
  assert.doesNotMatch(builderLibraryState, /recommendationSnapshot\.aggregate/);
  assert.doesNotMatch(builderLibraryState, /feedRead\.aggregate/);
  assert.equal(existsSync(join(root, "src/app/api/builders/library-stream/route.ts")), false);
  assert.match(builderLibraryEvents, /builderLibraryStatsChanged/);
  assert.doesNotMatch(builderLibraryEvents, /followBriefDataChanged/);
  assert.match(builderLibraryEvents, /builderLibrarySubscribeAll/);
  assert.match(buildersPage, /allowRemove:\s*false/);
  assert.match(builderSubscriptionRoute, /export async function PATCH/);
  assert.match(builderLibraryRoute, /export async function DELETE/);
  assert.match(builderLibraryRoute, /BuilderPoolOrigin\.HUB_IMPORT/);
  assert.match(builderLibraryRoute, /cannot be removed individually/);
  assert.match(builderSubscribeAllRoute, /export async function POST/);
  assert.doesNotMatch(builderSubscriptionRoute, /redirect\(/);
  assert.doesNotMatch(builderLibraryRoute, /redirect\(/);
  assert.doesNotMatch(builderSubscribeAllRoute, /redirect\(/);
  assert.doesNotMatch(hubPage, /sharePersonalLibraryToHubAction/);
  assert.doesNotMatch(hubPage, /importHubLibrariesAction/);
  assert.match(hubPage, /ensureDefaultCommunityLibraryImport\(session\.user\.id\)/);
  assert.match(hubPage, /LibraryHubImportForm/);
  assert.match(hubPage, /DigestPipelineImportForm/);
  assert.match(hubPage, /fb-hub-list/);
  assert.doesNotMatch(hubPage, /lg:grid-cols-2/);
  assert.match(hubPage, /digestPipelineShare\.findMany/);
  assert.match(hubPage, /digestPipelineImport\.findMany/);
  assert.match(hubPage, /Number\(b\.owned\) - Number\(a\.owned\)/);
  assert.match(hubPage, /adminCommunityLibraryName/);
  assert.match(hubPage, /library\.isFeatured/);
  assert.match(hubPage, /isAdminEmail\(library\.owner\?\.email\)/);
  assert.match(hubPage, /ownerLabel\(library\.owner, isCommunityLibrary\)/);
  assert.match(hubPage, /recordLibraryHubViews\(libraries\.map/);
  assert.match(dashboardPage, /DigestPipelineTitleEditor/);
  assert.match(dashboardPage, /ownPipelineShare\?\.title/);
  assert.match(dashboardPage, /ownPipelineShare\?\.isPublic === true/);
  assert.match(hubImportForm, /"use client"/);
  assert.match(hubImportForm, /fb-hub-list/);
  assert.match(hubImportForm, /fb-hub-title/);
  assert.match(hubImportForm, /fb-hub-card-actions/);
  assert.match(hubImportForm, /fb-hub-source-list/);
  assert.doesNotMatch(hubImportForm, /lg:grid-cols-2/);
  assert.doesNotMatch(hubImportForm, /serif mt-2 text-xl/);
  assert.match(globals, /\.fb-hub-list\s*{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/);
  assert.match(globals, /\.fb-hub-card\s*{[\s\S]*border-radius:\s*8px/);
  assert.match(globals, /\.fb-hub-card-stats\s*{[\s\S]*border-top:\s*1px solid var\(--line\)/);
  assert.match(hubImportForm, /fetch\("\/api\/library-hub\/imports"/);
  assert.match(hubImportForm, /isCommunity/);
  assert.match(hubImportForm, /counts\[filter\.key\]/);
  assert.match(hubImportForm, /function importLibrary\(libraryId: string\)/);
  assert.match(hubImportForm, /JSON\.stringify\(\{ libraryIds: \[libraryId\] \}\)/);
  assert.match(hubImportForm, /aria-label=\{`Import \$\{library\.name\}`\}/);
  assert.match(hubImportForm, /: "Import"/);
  assert.match(hubImportForm, /Importing/);
  assert.match(hubImportForm, /Imported/);
  assert.match(hubImportForm, /method: "DELETE"/);
  assert.match(hubImportForm, /Remove/);
  assert.doesNotMatch(hubImportForm, /Import selected/);
  assert.doesNotMatch(hubImportForm, /selectedIds/);
  assert.doesNotMatch(hubImportForm, /aria-pressed/);
  assert.doesNotMatch(hubImportForm, /hub-select-button/);
  assert.doesNotMatch(hubImportForm, /Deselect/);
  assert.doesNotMatch(hubImportForm, /hub-checkbox/);
  assert.doesNotMatch(hubImportForm, /library\.kind === "CENTRAL"/);
  assert.match(hubImportRoute, /export async function POST/);
  assert.match(hubImportRoute, /export async function DELETE/);
  assert.match(hubImportRoute, /importLibrariesFromHub/);
  assert.match(hubImportRoute, /removeLibraryImportFromHub/);
  assert.doesNotMatch(hubImportRoute, /redirect\(/);
  assert.match(libraryImportRemoveButton, /router\.refresh/);
  assert.match(libraryImportRemoveButton, /event\.stopPropagation/);
  assert.match(buildersPage, /LibraryImportRemoveButton/);
  assert.match(hubPage, /importCount/);
  assert.match(hubPage, /viewCount/);
  assert.match(hubPage, /orderBy:\s*\[\{ importCount: "desc" \}, \{ viewCount: "desc" \}/);
  assert.match(hubImportForm, /libraryId/);
  assert.match(digestPipelineForm, /"use client"/);
  assert.match(digestPipelineForm, /fb-hub-list/);
  assert.match(digestPipelineForm, /fb-hub-title/);
  assert.doesNotMatch(digestPipelineForm, /lg:grid-cols-2/);
  assert.match(digestPipelineForm, /Shared AI Digests/);
  assert.doesNotMatch(digestPipelineForm, /Share my digest/);
  assert.doesNotMatch(digestPipelineForm, /Remove my digest/);
  assert.doesNotMatch(digestPipelineForm, /ownPipelineShared/);
  assert.doesNotMatch(digestPipelineForm, /filter\(\(pipeline\) => !pipeline\.owned\)/);
  assert.match(digestPipelineForm, /Your digest/);
  assert.match(digestPipelineForm, /pipeline\.owned \? \(/);
  assert.match(digestPipelineVisibilityToggle, /Share to Hub/);
  assert.match(digestPipelineVisibilityToggle, /fetch\("\/api\/digest-pipelines\/share"/);
  assert.match(digestPipelineTitleEditor, /"use client"/);
  assert.match(digestPipelineTitleEditor, /Pencil/);
  assert.match(digestPipelineTitleEditor, /fetch\("\/api\/digest-pipelines\/share"/);
  assert.match(digestPipelineTitleEditor, /method: "PATCH"/);
  assert.match(digestPipelineTitleEditor, /router\.refresh/);
  assert.match(digestPipelineForm, /fetch\("\/api\/digest-pipelines\/imports"/);
  assert.match(digestPipelineForm, /fetch\(`\/api\/digest-pipelines\/imports\/\$\{pipelineId\}`/);
  assert.match(digestPipelineForm, /aria-label=\{`Import \$\{pipeline\.title\}`\}/);
  assert.match(digestPipelineForm, /Imported/);
  assert.match(digestPipelineForm, /Remove/);
  assert.match(digestPipelineShareRoute, /shareDigestPipelineToHub/);
  assert.match(digestPipelineShareRoute, /updateDigestPipelineTitle/);
  assert.match(digestPipelineShareRoute, /export async function PATCH/);
  assert.match(digestPipelineShareRoute, /unshareDigestPipelineFromHub/);
  assert.match(digestPipelineImportRoute, /importDigestPipelineFromHub/);
  assert.match(digestPipelineRemoveRoute, /removeDigestPipelineImportFromHub/);
  assert.match(visibilityRoute, /unsharePersonalLibraryFromHub/);
  assert.equal(existsSync(join(root, "src/app/actions.ts")), false);
  assert.match(skillRoute, /syncPersonalLibraryHubForUser/);
  assert.match(skillRoute, /fetchTool: "Legacy fetch\/import"/);
  assert.match(schema, /model LibraryHubEntry/);
  assert.match(schema, /model LibraryImport/);
  assert.match(schema, /model DigestPipelineShare \{/);
  assert.match(schema, /headlineSummary\s+String\?/);
  assert.match(schema, /ownerUserId\s+String/);
  assert.match(schema, /importCount\s+Int\s+@default\(0\)/);
  assert.match(schema, /@@unique\(\[ownerUserId\]\)/);
  assert.match(schema, /model DigestPipelineImport \{/);
  assert.match(schema, /@@id\(\[userId, pipelineId\]\)/);
  assert.match(schema, /UserLibraryVisibility/);
  assert.match(source("src/lib/library-hub.ts"), /shareDigestPipelineToHub/);
  assert.match(source("src/lib/library-hub.ts"), /updateDigestPipelineTitle/);
  assert.match(source("src/lib/library-hub.ts"), /isPublic: existing\?\.isPublic \?\? false/);
  assert.match(source("src/lib/library-hub.ts"), /importDigestPipelineFromHub/);
  assert.match(source("src/lib/library-hub.ts"), /removeDigestPipelineImportFromHub/);
  assert.match(source("src/lib/library-hub.ts"), /digestPipelineTitle/);
  assert.match(source("src/lib/library-hub.ts"), /displayDigestPipelineTitle/);
  assert.match(source("src/lib/library-hub.ts"), /\$\{identity\}'s AI Digest/);
  assert.doesNotMatch(source("src/lib/library-hub.ts"), /\$\{identity\}'s AI Builder Digest/);
  assert.match(builderPool, /ensureDefaultCommunityLibraryImport/);
  assert.match(builderPool, /isAdminEmail\(user\.email\)/);
  assert.match(builderPool, /userLibraryVisibility/);
  assert.match(builderPool, /BuilderPoolOrigin\.HUB_IMPORT/);
  assert.match(builderPool, /prisma\.libraryImport/);
  // A HUB_IMPORT must never downgrade a user's own PERSONAL_SYNC pool entry
  // (would make it non-removable + hide it from the private library). Guarded
  // in both addBuilderToPool (upsert) and ensureDefaultCommunityLibraryImport
  // (raw updateMany).
  assert.match(builderPool, /existing\?\.origin === BuilderPoolOrigin\.PERSONAL_SYNC/);
  assert.match(builderPool, /origin: \{ not: BuilderPoolOrigin\.PERSONAL_SYNC \}/);
  // Library import preview is capped (page take: 200); show an honest "first N
  // of M" notice instead of silently truncating below the reported count.
  assert.match(
    hubImportForm,
    /<CountRange>[\s\S]*Showing \{formatCount\(library\.items\.length\)\} of \{formatCount\(library\.itemCount\)\} sources/,
  );
});

test("settings mutations stay local instead of refreshing the whole route", () => {
  const settingsPage = source("src/app/(workspace)/settings/page.tsx");
  const skillPromptActions = source("src/components/SkillPromptActions.tsx");
  const tokenPanel = source("src/components/AgentTokenPanel.tsx");
  const digestMaxAgeRoute = source("src/app/api/settings/digest-max-age/route.ts");
  const tokensRoute = source("src/app/api/settings/tokens/route.ts");
  const tokenRoute = source("src/app/api/settings/tokens/[tokenId]/route.ts");
  const globals = source("src/app/globals.css");

  // The Feed preferences module is gone; the digest max-age editor now lives in
  // the digest prompt dialogs, persisted via the dedicated digest-max-age route.
  assert.doesNotMatch(settingsPage, /FeedPreferenceForm/);
  assert.match(settingsPage, /AgentTokenPanel/);
  assert.match(settingsPage, /settings-workspace/);
  assert.match(settingsPage, /settings-access-grid/);
  assert.doesNotMatch(settingsPage, /lg:grid-cols-2/);
  assert.doesNotMatch(settingsPage, /settings-access-grid grid gap-5/);
  assert.match(settingsPage, /className="settings-rules"/);
  assert.match(settingsPage, /className="settings-rules-title fb-section-heading"/);
  assert.match(settingsPage, /className="settings-rules-summary"/);
  assert.match(settingsPage, /className="settings-rules-summary-desc"/);
  assert.match(settingsPage, /className="settings-rules-body"/);
  assert.match(settingsPage, /className="settings-config-form settings-config-form--common"/);
  assert.match(settingsPage, /className="settings-rules settings-rules-skeleton"/);
  assert.match(settingsPage, /className="settings-rules-skeleton-list"/);
  assert.match(settingsPage, /className="settings-skeleton-line settings-skeleton-line--eyebrow"/);
  assert.match(settingsPage, /className="settings-skeleton-line settings-skeleton-line--title"/);
  assert.match(settingsPage, /className="settings-skeleton-card"/);
  assert.match(settingsPage, /className="settings-skeleton-line settings-skeleton-line--access-title"/);
  assert.match(settingsPage, /className="settings-skeleton-line settings-skeleton-line--access-desc"/);
  assert.match(settingsPage, /className="settings-skeleton-pill"/);
  assert.match(settingsPage, /className="settings-skeleton-row"/);
  assert.doesNotMatch(settingsPage, /animate-pulse rounded bg-\[var\(--paper-strong\)\]|className="h-/);
  assert.doesNotMatch(settingsPage, /settings-rules grid gap-4/);
  assert.doesNotMatch(settingsPage, /fb-section-heading mt-1/);
  assert.doesNotMatch(settingsPage, /settings-rules-summary flex cursor-pointer/);
  assert.doesNotMatch(settingsPage, /settings-rules-body mt-4/);
  assert.doesNotMatch(settingsPage, /settings-config-form mb-4 grid gap-4/);
  assert.doesNotMatch(settingsPage, /mt-5 grid gap-3/);
  assert.doesNotMatch(settingsPage, /settings-access-grid mt-6/);
  assert.doesNotMatch(settingsPage, /settings-rules mt-10/);
  assert.match(globals, /\.settings-workspace\s*{[\s\S]*margin-top:\s*clamp/);
  assert.match(globals, /\.settings-access-grid\s*{[\s\S]*max-width:\s*52rem/);
  assert.match(globals, /\.settings-access-grid\s*{[\s\S]*display:\s*grid/);
  assert.match(globals, /\.settings-rules\s*{[\s\S]*display:\s*grid/);
  assert.match(globals, /\.settings-rules-head\s*{[\s\S]*border-bottom:/);
  assert.match(globals, /\.settings-rules-summary\s*{[\s\S]*cursor:\s*pointer/);
  assert.match(globals, /\.settings-rules-summary-desc/);
  assert.match(globals, /\.settings-rules-skeleton-list/);
  assert.match(globals, /\.settings-skeleton-line,[\s\S]*\.settings-skeleton-row\s*{[\s\S]*color-mix\(in oklch, var\(--ink\) 10%, transparent\)/);
  assert.match(globals, /\.settings-skeleton-pill\s*{[\s\S]*border-radius:\s*999px/);
  assert.doesNotMatch(globals, /border-left:\s*[2-9]/);
  assert.doesNotMatch(settingsPage, /createPersonalTokenAction/);
  assert.doesNotMatch(settingsPage, /revokeTokenAction/);
  assert.doesNotMatch(settingsPage, /updateFeedPreferenceAction/);
  assert.doesNotMatch(settingsPage, /FormSubmitButton/);
  assert.match(skillPromptActions, /"use client"/);
  assert.match(skillPromptActions, /fetch\("\/api\/settings\/digest-max-age"/);
  assert.match(tokenPanel, /"use client"/);
  assert.match(tokenPanel, /fetch\("\/api\/settings\/tokens"/);
  assert.match(tokenPanel, /fetch\(`\/api\/settings\/tokens\/\$\{tokenId\}`/);
  assert.match(tokenPanel, /"New access key"/);
  assert.match(tokenPanel, /fb-dialog/);
  assert.match(tokenPanel, /className="access-keys-panel fb-panel"/);
  assert.match(tokenPanel, /className="access-keys-head"/);
  assert.match(tokenPanel, /className="access-keys-list"/);
  assert.match(tokenPanel, /className="access-keys-more"/);
  assert.match(tokenPanel, /className="access-keys-empty"/);
  assert.match(tokenPanel, /className="fb-dialog-inner settings-dialog-stack"/);
  assert.match(tokenPanel, /className="settings-dialog-copy"/);
  assert.match(tokenPanel, /className="settings-dialog-actions"/);
  assert.match(tokenPanel, /className="access-key-name"/);
  assert.doesNotMatch(tokenPanel, /className="mt-/);
  assert.doesNotMatch(tokenPanel, /className="[^"]* mt-/);
  assert.match(settingsPage, /className="access-keys-list access-keys-list--skeleton"/);
  assert.doesNotMatch(settingsPage, /mt-4 h-11 animate-pulse/);
  assert.match(globals, /\.access-keys-panel/);
  assert.match(globals, /\.settings-dialog-stack/);
  assert.match(digestMaxAgeRoute, /export async function PATCH/);
  assert.match(digestMaxAgeRoute, /userFeedPreference\.upsert/);
  assert.match(digestMaxAgeRoute, /digestMaxPostAgeDays/);
  assert.match(digestMaxAgeRoute, /NextResponse\.json/);
  assert.doesNotMatch(digestMaxAgeRoute, /redirect\(/);
  assert.match(tokensRoute, /export async function POST/);
  assert.match(tokensRoute, /createAgentToken/);
  assert.doesNotMatch(tokensRoute, /redirect\(/);
  assert.match(tokenRoute, /export async function DELETE/);
  // Revoke is a SOFT delete: stamp revokedAt (keeps the row + audit trail +
  // "Revoked [date]" UI), never a hard row delete.
  assert.match(tokenRoute, /agentToken\.updateMany/);
  assert.match(tokenRoute, /revokedAt: new Date\(\)/);
  assert.doesNotMatch(tokenRoute, /agentToken\.deleteMany/);
  assert.doesNotMatch(tokenRoute, /redirect\(/);
});

test("list actions use compact controls instead of full-width mobile buttons", () => {
  const css = source("src/app/globals.css");
  const builderLibraryList = source("src/components/BuilderLibraryList.tsx");
  const builderActions = source("src/components/BuilderLibraryActions.tsx");
  const settingsPage = source("src/app/(workspace)/settings/page.tsx");
  const agentTokenPanel = source("src/components/AgentTokenPanel.tsx");

  assert.match(css, /\.button-compact/);
  assert.match(css, /\.row-actions/);
  assert.match(css, /\.source-summary-line/);
  assert.match(css, /\.sources-sync-section \.digest-updates-panel/);
  assert.match(css, /\.builder-library-card-main\s*{\s*\n\s*grid-template-columns:\s*2rem minmax\(0,\s*1fr\) auto/);
  assert.doesNotMatch(css, /\.builder-library-stats\s*{/);
  assert.match(css, /\.builder-posts-latest/);
  assert.match(css, /\.builder-posts-latest::before\s*{[\s\S]*content:\s*"·"/);
  assert.match(css, /\.builder-posts-summary\s*{[\s\S]*display:\s*inline-flex/);
  assert.match(css, /\.builder-posts > summary\s*{[\s\S]*display:\s*flex/);
  assert.match(css, /\.builder-library-row-tools\s*{[\s\S]*opacity:\s*0/);
  assert.doesNotMatch(css, /\.library-section-summary::after[\s\S]*content:\s*"\+"/);
  assert.match(css, /@media \(max-width:\s*767px\)[\s\S]*\.builder-library-card-main\s*{[\s\S]*grid-template-areas:[\s\S]*"avatar info"[\s\S]*"\. actions"/);
  assert.match(css, /@media \(max-width:\s*767px\)[\s\S]*\.library-section-meta\s*{[\s\S]*display:\s*grid/);
  assert.match(css, /@media \(max-width:\s*767px\)[\s\S]*\.page-pad h2\s*{[\s\S]*font-size:\s*1\.25rem/);
  assert.match(css, /@media \(max-width:\s*767px\)[\s\S]*\.fb-panel\s*{[\s\S]*padding:\s*0\.95rem/);
  assert.doesNotMatch(css, /\.builder-row form,\s*\n\s*\.builder-row button\s*{\s*\n\s*width:\s*100%/);
  assert.match(builderLibraryList, /builder-library-card-main/);
  assert.doesNotMatch(builderLibraryList, /BuilderStats/);
  assert.match(builderLibraryList, /builder-library-row-tools/);
  assert.match(source("src/components/BuilderFeedItems.tsx"), /className="builder-posts-summary"/);
  assert.match(builderActions, /fb-btn/);
  assert.match(builderActions, /builder-library-follow-toggle/);
  assert.match(settingsPage, /AgentTokenPanel/);
  assert.match(agentTokenPanel, /fb-btn/);
});
